import React, { useState, useEffect } from "react";
import {
  Card, Table, DatePicker, Select, Tabs, Modal, Tag, Tooltip,
  Dropdown, Pagination, Skeleton, Empty, Result, ConfigProvider, Popconfirm, Switch, Progress
} from "antd";
import {
  ResponsiveContainer, LineChart, Line, XAxis, YAxis,
  Tooltip as RechartsTooltip, Legend, PieChart, Pie, Cell
} from "recharts";
import {
  TrendingUp, TrendingDown, DollarSign, Calendar, RefreshCw,
  Download, Search, Eye, Edit, Trash2, CheckSquare,
  AlertCircle, FileText, PieChart as PieIcon, Plus, CheckCircle, Clock,
  Play, ShieldAlert, Mail, Activity, Sparkles, Filter, ChevronDown, ListFilter
} from "lucide-react";
import { useReports } from "./hooks/useReports";
import { mockStores } from "./mockData";
import GenerateReportModal from "./components/GenerateReportModal";
import ReportDetailsModal from "./components/ReportDetailsModal";
import ScheduleReportModal from "./components/ScheduleReportModal";
import ScheduleDetailsDrawer from "./components/ScheduleDetailsDrawer";
import DeleteConfirmationModal from "./components/DeleteConfirmationModal";
import dayjs from "dayjs";
import { toast } from "sonner";
import emptyReportsWebp from "../../../../../assets/empty_reports.webp";

const { TabPane } = Tabs;

export default function Reports() {
  const reportsHook = useReports();
  const {
    loading,
    search,
    setSearch,
    reportType,
    setReportType,
    status,
    setStatus,
    generatedBy,
    setGeneratedBy,
    dateFilter,
    setDateFilter,
    customRange,
    setCustomRange,

    currentPage,
    setCurrentPage,
    pageSize,
    setPageSize,
    sortBy,
    setSortBy,
    sortOrder,
    setSortOrder,

    selectedRowKeys,
    setSelectedRowKeys,

    selectedReport,
    setSelectedReport,
    selectedSchedule,
    setSelectedSchedule,

    statistics,
    reportsByTypeChartData,
    reportTrendChartData,
    usersList,
    tableData,
    totalRecords,

    schedulesTableData,

    generateReport,
    downloadReport,
    retryReport,
    deleteReport,
    scheduleReport,
    updateSchedule,
    toggleScheduleActive,
    deleteSchedule,
    runScheduleNow,

    bulkDownloadSelected,
    bulkDeleteSelected,
    bulkExportCSV,
    refetch
  } = reportsHook;

  // Local state for UI
  const [localSearch, setLocalSearch] = useState(search);
  const [showGenerateModal, setShowGenerateModal] = useState(false);
  const [showScheduleModal, setShowScheduleModal] = useState(false);
  const [showDetailsModal, setShowDetailsModal] = useState(false);
  const [showScheduleDrawer, setShowScheduleDrawer] = useState(false);
  const [showDeleteModal, setShowDeleteModal] = useState(false);
  const [showDeleteScheduleModal, setShowDeleteScheduleModal] = useState(false);
  const [itemToDelete, setItemToDelete] = useState(null);
  const [isError, setIsError] = useState(false);

  // Sync local search with debounce state
  useEffect(() => {
    setSearch(localSearch);
    setCurrentPage(1);
  }, [localSearch, setSearch, setCurrentPage]);

  // Date Range labels mapping
  const dateLabels = {
    "Today": "Today",
    "Last 7 Days": "Last 7 Days",
    "This Month": "This Month",
    "Custom": "Custom Range"
  };

  const getStatusColor = (st) => {
    switch (st) {
      case "Completed": return "green";
      case "Generating": return "orange";
      case "Failed": return "red";
      default: return "blue";
    }
  };

  // Columns for Generated Reports Log Table
  const columns = [
    {
      title: "Report No",
      dataIndex: "reportNumber",
      key: "reportNumber",
      sorter: true,
      className: "font-bold text-zinc-700 dark:text-zinc-300"
    },
    {
      title: "Type",
      dataIndex: "reportType",
      key: "reportType",
      sorter: true,
      render: val => (
        <span className="font-bold text-zinc-800 dark:text-zinc-200">
          {val}
        </span>
      )
    },
    {
      title: "Date Range",
      key: "dateRange",
      render: (_, r) => (
        <span className="text-zinc-500 font-semibold">
          {r.startDate} to {r.endDate}
        </span>
      )
    },
    {
      title: "Generated By",
      dataIndex: "generatedBy",
      key: "generatedBy",
      render: val => <span className="text-zinc-600 dark:text-zinc-400 font-semibold">{val}</span>
    },
    {
      title: "Generated At",
      dataIndex: "createdAt",
      key: "createdAt",
      sorter: true,
      render: val => <span>{new Date(val).toLocaleString("en-IN", { day: "2-digit", month: "short", hour: "2-digit", minute: "2-digit" })}</span>
    },
    {
      title: "Status",
      dataIndex: "status",
      key: "status",
      sorter: true,
      render: st => (
        <Tag color={getStatusColor(st)} className="font-extrabold text-[9px] uppercase border-0 px-2 py-0.5 rounded">
          {st}
        </Tag>
      )
    },
    {
      title: "Actions",
      key: "actions",
      align: "center",
      render: (_, record) => {
        const items = [
          {
            key: "view",
            label: (
              <span className="flex items-center gap-2 text-xs font-semibold text-zinc-700 dark:text-zinc-200 py-1">
                <Eye size={13} className="text-zinc-400 dark:text-zinc-500" />
                <span>View Details</span>
              </span>
            ),
            onClick: () => {
              setSelectedReport(record);
              setShowDetailsModal(true);
            }
          },
          ...(record.status === "Completed" ? [{
            key: "download",
            label: (
              <span className="flex items-center gap-2 text-xs font-semibold text-zinc-700 dark:text-zinc-200 py-1">
                <Download size={13} className="text-zinc-400 dark:text-zinc-500" />
                <span>Download File</span>
              </span>
            ),
            onClick: () => downloadReport(record._id)
          }] : []),
          ...(record.status === "Failed" ? [{
            key: "retry",
            label: (
              <span className="flex items-center gap-2 text-xs font-semibold text-zinc-700 dark:text-zinc-200 py-1">
                <RefreshCw size={13} className="text-zinc-400 dark:text-zinc-500" />
                <span>Retry Generation</span>
              </span>
            ),
            onClick: () => retryReport(record._id)
          }] : [])
        ];

        return (
          <div className="flex items-center justify-center gap-1.5">
            <Dropdown menu={{ items }} placement="bottomRight" trigger={["click"]}>
              <button className="flex items-center gap-1 px-2.5 py-1 text-[9px] font-black uppercase rounded-lg bg-zinc-150 hover:bg-zinc-250 dark:bg-zinc-850 dark:hover:bg-zinc-800 text-zinc-750 dark:text-zinc-200 transition-all duration-200 cursor-pointer shadow-xs">
                Options
              </button>
            </Dropdown>

            <button
              onClick={() => {
                setItemToDelete(record._id);
                setShowDeleteModal(true);
              }}
              className="p-1 text-zinc-400 hover:text-rose-500 transition-colors cursor-pointer rounded-lg hover:bg-rose-50/50"
            >
              <Trash2 size={13} />
            </button>
          </div>
        );
      }
    }
  ];

  // Columns for Scheduled Reports Table
  const scheduleColumns = [
    {
      title: "Report Type",
      dataIndex: "reportType",
      key: "reportType",
      className: "font-bold text-zinc-700 dark:text-zinc-300"
    },
    {
      title: "Frequency",
      dataIndex: "frequency",
      key: "frequency",
      render: freq => (
        <Tag color="purple" className="font-extrabold text-[9px] uppercase border-0 px-2 py-0.5 rounded">
          {freq}
        </Tag>
      )
    },
    {
      title: "Format",
      dataIndex: "format",
      key: "format",
      render: fmt => (
        <span className="font-bold text-zinc-650 dark:text-zinc-300">{fmt}</span>
      )
    },
    {
      title: "Next Run",
      dataIndex: "nextRun",
      key: "nextRun",
      render: val => <span>{new Date(val).toLocaleString("en-IN", { day: "2-digit", month: "short", hour: "2-digit", minute: "2-digit" })}</span>
    },
    {
      title: "Active",
      dataIndex: "active",
      key: "active",
      render: (isActive, record) => (
        <Switch
          checked={isActive}
          onChange={() => toggleScheduleActive(record._id)}
          checkedChildren="ON"
          unCheckedChildren="OFF"
          size="small"
        />
      )
    },
    {
      title: "Actions",
      key: "actions",
      align: "center",
      render: (_, record) => (
        <div className="flex items-center justify-center gap-2">
          <button
            onClick={() => {
              setSelectedSchedule(record);
              setShowScheduleModal(true);
            }}
            className="flex items-center justify-center p-1.5 bg-zinc-100 hover:bg-zinc-200 dark:bg-zinc-800 dark:hover:bg-zinc-750 text-zinc-600 dark:text-zinc-300 rounded-lg cursor-pointer transition-colors"
            title="Edit Schedule"
          >
            <Edit size={12} />
          </button>
          <button
            onClick={() => runScheduleNow(record._id)}
            className="flex items-center justify-center p-1.5 bg-emerald-500/10 hover:bg-emerald-500 text-emerald-600 hover:text-white rounded-lg cursor-pointer transition-all"
            title="Run Now"
          >
            <Play size={12} fill="currentColor" className="ml-0.5" />
          </button>
          <button
            onClick={() => {
              setItemToDelete(record._id);
              setShowDeleteScheduleModal(true);
            }}
            className="flex items-center justify-center p-1.5 bg-rose-500/10 hover:bg-rose-600 text-rose-600 hover:text-white rounded-lg cursor-pointer transition-all"
            title="Delete Schedule"
          >
            <Trash2 size={12} />
          </button>
        </div>
      )
    }
  ];

  // Sorting Handler
  const handleTableChange = (pagination, filters, sorter) => {
    if (sorter.field) {
      setSortBy(sorter.field);
      setSortOrder(sorter.order === "ascend" ? "asc" : "desc");
      setCurrentPage(1);
    }
  };

  const handleResetFilters = () => {
    setLocalSearch("");
    setReportType("All");
    setStatus("All");
    setGeneratedBy("All");
    setDateFilter("This Month");
    setCustomRange({ start: null, end: null });
    setCurrentPage(1);
  };

  const handleRowClick = (record) => {
    setSelectedSchedule(record);
    setShowScheduleDrawer(true);
  };

  const rowSelection = {
    selectedRowKeys,
    onChange: (keys) => setSelectedRowKeys(keys)
  };

  if (isError) {
    return (
      <ConfigProvider theme={{ token: { fontFamily: "'Poppins', system-ui, sans-serif" } }}>
        <div className="p-8 min-h-[80vh] flex items-center justify-center bg-slate-50 dark:bg-zinc-950">
          <Result
            status="error"
            title="Unable to load reports."
            subTitle="A network error occurred while communicating with the reports and background workers database. Please retry your request."
            extra={[
              <button
                key="retry"
                onClick={() => {
                  setIsError(false);
                  refetch();
                }}
                className="px-5 py-2 bg-[var(--primary)] hover:opacity-95 text-white font-extrabold uppercase transition-all rounded-lg cursor-pointer text-xs shadow-md"
              >
                Retry
              </button>
            ]}
          />
        </div>
      </ConfigProvider>
    );
  }

  return (
    <ConfigProvider theme={{ token: { fontFamily: "'Poppins', system-ui, sans-serif", colorPrimary: localStorage.getItem("sa_primary") || "#a43c12" } }}>
      <div className="p-3 md:p-5 max-w-7xl mx-auto space-y-4 text-xs bg-slate-50 dark:bg-zinc-950 min-h-screen text-zinc-700 dark:text-zinc-300 font-['Poppins']">
        <style>{`
          .ant-select, .ant-select-item, .ant-picker, .ant-picker-input > input, .ant-table, .ant-table-cell, .ant-tabs, .ant-tabs-tab-btn, .ant-modal, .ant-modal-title, .ant-drawer, .ant-pagination, .ant-pagination-item, .ant-tag, .ant-empty {
            font-family: 'Poppins', system-ui, -apple-system, sans-serif !important;
          }
          .ant-switch-checked {
            background-color: var(--primary) !important;
          }
        `}</style>

        {/* 1. Header Section */}
        <header className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 bg-white dark:bg-zinc-900 border border-zinc-200 dark:border-zinc-800 p-4 rounded-xl shadow-xs shrink-0">
          <div>
            <div className="flex items-center gap-2">
              <h1 className="text-xl font-black tracking-tight text-slate-900 dark:text-white">
                Reports
              </h1>
              <span className="bg-blue-500/10 text-blue-600 text-[8px] font-bold px-1.5 py-0.2 rounded-full border border-blue-500/20 uppercase tracking-widest animate-pulse">
                BullMQ Active
              </span>
            </div>
            <p className="text-zinc-450 dark:text-zinc-400 mt-0.5 text-[10px] font-semibold">
              Generate, monitor and schedule analytics reports.
            </p>
          </div>

          <div className="flex items-center gap-2 shrink-0 flex-wrap">
            <button
              onClick={() => {
                setSelectedSchedule(null);
                setShowScheduleModal(true);
              }}
              className="flex items-center justify-center gap-1.5 px-4 py-2 border border-zinc-250 dark:border-zinc-800 hover:border-[var(--primary)] hover:text-[var(--primary)] text-zinc-700 dark:text-zinc-200 rounded-lg shadow-sm font-extrabold transition-all duration-200 cursor-pointer text-[10px] uppercase active:scale-[0.97] h-8"
            >
              <Calendar size={13} />
              <span>Schedule Report</span>
            </button>

            <button
              onClick={() => setShowGenerateModal(true)}
              className="flex items-center justify-center gap-1.5 px-4 py-2 bg-[var(--primary)] hover:bg-[var(--primary-hover)] hover:opacity-95 text-white rounded-lg shadow-md font-extrabold transition-all duration-200 cursor-pointer text-[10px] uppercase active:scale-[0.97] h-8"
            >
              <Plus size={14} />
              <span>Generate Report</span>
            </button>

            <button
              onClick={() => refetch()}
              className="flex items-center justify-center p-2 bg-zinc-100 hover:bg-zinc-250 dark:bg-zinc-800 dark:hover:bg-zinc-750 text-zinc-700 dark:text-zinc-200 rounded-lg shadow-sm transition-all duration-200 cursor-pointer active:scale-[0.95] h-8 w-8"
              title="Refresh Reports Log"
            >
              <RefreshCw size={13} className={loading ? "animate-spin text-[var(--primary)]" : "text-[var(--primary)]"} />
            </button>

            <button
              className="text-[9px] font-semibold text-zinc-400 hover:text-rose-500 cursor-pointer transition-colors"
              onClick={() => setIsError(true)}
              title="Test simulated error page state"
            >
              Trigger Error State
            </button>
          </div>
        </header>

        {/* 2. KPI Cards Section */}
        <section className="grid grid-cols-2 lg:grid-cols-4 gap-4">
          {/* Card 1: Reports Generated */}
          <Card size="small" className="shadow-xs border border-zinc-200 dark:border-zinc-800 rounded-xl" bodyStyle={{ padding: "14px" }}>
            <div className="flex justify-between items-start">
              <div>
                <span className="text-zinc-400 dark:text-zinc-500 uppercase text-[9px] font-black tracking-wider">Reports Generated</span>
                {loading ? (
                  <Skeleton.Input active size="small" className="mt-1" />
                ) : (
                  <h3 className="text-xl font-black text-blue-600 mt-1">
                    {statistics.generatedCount}
                  </h3>
                )}
                <span className="text-[10px] text-zinc-450 block mt-0.5">BullMQ completed compiles</span>
              </div>
              <div className="p-2 rounded-lg bg-blue-50 dark:bg-blue-950/20 text-blue-500 shrink-0">
                <CheckCircle size={16} />
              </div>
            </div>
          </Card>

          {/* Card 2: Scheduled Reports */}
          <Card size="small" className="shadow-xs border border-zinc-200 dark:border-zinc-800 rounded-xl" bodyStyle={{ padding: "14px" }}>
            <div className="flex justify-between items-start">
              <div>
                <span className="text-zinc-400 dark:text-zinc-500 uppercase text-[9px] font-black tracking-wider">Scheduled Loops</span>
                {loading ? (
                  <Skeleton.Input active size="small" className="mt-1" />
                ) : (
                  <h3 className="text-xl font-black text-purple-600 mt-1">
                    {statistics.scheduledCount}
                  </h3>
                )}
                <span className="text-[10px] text-zinc-450 block mt-0.5">Automated cron loops</span>
              </div>
              <div className="p-2 rounded-lg bg-purple-50 dark:bg-purple-950/20 text-purple-500 shrink-0">
                <Clock size={16} />
              </div>
            </div>
          </Card>

          {/* Card 3: Failed Reports */}
          <Card size="small" className="shadow-xs border border-zinc-200 dark:border-zinc-800 rounded-xl" bodyStyle={{ padding: "14px" }}>
            <div className="flex justify-between items-start">
              <div>
                <span className="text-zinc-400 dark:text-zinc-500 uppercase text-[9px] font-black tracking-wider">Failed Runs</span>
                {loading ? (
                  <Skeleton.Input active size="small" className="mt-1" />
                ) : (
                  <h3 className="text-xl font-black text-rose-600 mt-1">
                    {statistics.failedCount}
                  </h3>
                )}
                <span className="text-[10px] text-zinc-450 block mt-0.5">Awaiting manual retry</span>
              </div>
              <div className="p-2 rounded-lg bg-rose-50 dark:bg-rose-950/20 text-rose-500 shrink-0">
                <ShieldAlert size={16} />
              </div>
            </div>
          </Card>

          {/* Card 4: Downloaded Reports */}
          <Card size="small" className="shadow-xs border border-zinc-200 dark:border-zinc-800 rounded-xl" bodyStyle={{ padding: "14px" }}>
            <div className="flex justify-between items-start">
              <div>
                <span className="text-zinc-400 dark:text-zinc-500 uppercase text-[9px] font-black tracking-wider">Downloaded Files</span>
                {loading ? (
                  <Skeleton.Input active size="small" className="mt-1" />
                ) : (
                  <h3 className="text-xl font-black text-emerald-600 mt-1">
                    {statistics.downloadCountSum}
                  </h3>
                )}
                <span className="text-[10px] text-zinc-450 block mt-0.5">Cumulative files downloaded</span>
              </div>
              <div className="p-2 rounded-lg bg-emerald-50 dark:bg-emerald-950/20 text-emerald-600 shrink-0">
                <Download size={16} />
              </div>
            </div>
          </Card>
        </section>

        {/* 3. Analytics Section (Charts) */}
        <section className="grid grid-cols-1 md:grid-cols-2 gap-4">
          {/* Pie Chart */}
          <Card className="shadow-xs border border-zinc-200 dark:border-zinc-800 rounded-xl" bodyStyle={{ padding: "16px" }}>
            <div className="flex justify-between items-center mb-3">
              <div>
                <h3 className="font-extrabold text-xs text-zinc-805 dark:text-zinc-150 flex items-center gap-1.5 uppercase">
                  <PieIcon size={14} className="text-[var(--primary)]" />
                  Reports By Category
                </h3>
                <span className="text-[8px] font-bold text-zinc-400 uppercase">Share of compiled documents by type</span>
              </div>
            </div>

            {loading ? (
              <Skeleton active paragraph={{ rows: 5 }} />
            ) : reportsByTypeChartData.length > 0 ? (
              <div className="grid grid-cols-5 gap-3 items-center">
                <div className="col-span-2 h-[200px] w-full relative">
                  <ResponsiveContainer width="100%" height="100%">
                    <PieChart>
                      <Pie
                        data={reportsByTypeChartData}
                        cx="50%"
                        cy="50%"
                        innerRadius={45}
                        outerRadius={75}
                        paddingAngle={3}
                        dataKey="value"
                      >
                        {reportsByTypeChartData.map((entry, index) => (
                          <Cell key={`cell-${index}`} fill={entry.color} />
                        ))}
                      </Pie>
                      <RechartsTooltip />
                    </PieChart>
                  </ResponsiveContainer>
                </div>
                <div className="col-span-3 space-y-1.5 max-h-[200px] overflow-y-auto pr-1">
                  {reportsByTypeChartData.map((item, idx) => (
                    <div key={idx} className="flex justify-between items-center p-1 border rounded-lg bg-zinc-50/50 dark:bg-zinc-900/40 text-[10px]">
                      <div className="flex items-center gap-1.5 text-[9px] font-bold text-zinc-650 truncate max-w-[120px]">
                        <span className="w-1.5 h-1.5 rounded-full shrink-0" style={{ backgroundColor: item.color }} />
                        <span className="truncate">{item.name}</span>
                      </div>
                      <span className="font-black text-zinc-800 dark:text-zinc-150">{item.value} run(s)</span>
                    </div>
                  ))}
                </div>
              </div>
            ) : (
              <div className="h-[200px] flex items-center justify-center">
                <Empty image={Empty.PRESENTED_IMAGE_SIMPLE} description="No category data compiling." />
              </div>
            )}
          </Card>

          {/* Line Chart */}
          <Card className="shadow-xs border border-zinc-200 dark:border-zinc-800 rounded-xl" bodyStyle={{ padding: "16px" }}>
            <div className="flex justify-between items-center mb-3">
              <div>
                <h3 className="font-extrabold text-xs text-zinc-805 dark:text-zinc-150 flex items-center gap-1.5 uppercase">
                  <TrendingUp size={14} className="text-[var(--primary)]" />
                  Report Generation Trend
                </h3>
                <span className="text-[8px] font-bold text-zinc-400 uppercase">Daily generated reports load velocity</span>
              </div>
            </div>

            <div className="h-[200px] w-full">
              {loading ? (
                <Skeleton active paragraph={{ rows: 5 }} />
              ) : reportTrendChartData.length > 0 ? (
                <ResponsiveContainer width="100%" height="100%">
                  <LineChart data={reportTrendChartData} margin={{ top: 5, right: 5, left: -25, bottom: 0 }}>
                    <XAxis dataKey="formattedDate" stroke="#888888" fontSize={9} tickLine={false} axisLine={false} />
                    <YAxis stroke="#888888" fontSize={9} tickLine={false} axisLine={false} allowDecimals={false} />
                    <RechartsTooltip
                      contentStyle={{ backgroundColor: "rgba(255, 255, 255, 0.95)", borderRadius: "8px", fontSize: "10px" }}
                      formatter={(v) => [v, "Reports Run"]}
                    />
                    <Line type="monotone" dataKey="count" stroke="var(--primary)" strokeWidth={2.2} activeDot={{ r: 6 }} />
                  </LineChart>
                </ResponsiveContainer>
              ) : (
                <div className="h-full flex items-center justify-center">
                  <Empty image={Empty.PRESENTED_IMAGE_SIMPLE} description="No trend data compiling." />
                </div>
              )}
            </div>
          </Card>
        </section>

        {/* 4. Bulk Actions Floating Toolbar */}
        {selectedRowKeys.length > 0 && (
          <div className="flex items-center justify-between p-3 bg-zinc-950 text-white rounded-xl shadow-lg animate-fade-up sticky bottom-4 z-50">
            <div className="flex items-center gap-2 text-[10px] font-bold">
              <CheckSquare size={14} className="text-[var(--primary)]" />
              <span>{selectedRowKeys.length} report(s) selected</span>
            </div>
            <div className="flex items-center gap-2">
              <button
                onClick={bulkDownloadSelected}
                className="px-3.5 py-1.5 bg-emerald-600 hover:bg-emerald-700 text-white font-bold text-[9px] uppercase rounded-lg transition-colors cursor-pointer"
              >
                Download Selected
              </button>
              <button
                onClick={() => {
                  setItemToDelete(selectedRowKeys);
                  setShowDeleteModal(true);
                }}
                className="px-3.5 py-1.5 bg-rose-600 hover:bg-rose-700 text-white font-bold text-[9px] uppercase rounded-lg transition-colors cursor-pointer"
              >
                Delete Selected
              </button>
              <button
                onClick={bulkExportCSV}
                className="px-3.5 py-1.5 bg-[var(--primary)] hover:opacity-95 text-white font-bold text-[9px] uppercase rounded-lg transition-all cursor-pointer"
              >
                Export List (CSV)
              </button>
              <div className="border-l h-5 border-zinc-800 mx-1"></div>
              <button
                onClick={() => setSelectedRowKeys([])}
                className="p-1 text-zinc-400 hover:text-white transition-colors cursor-pointer"
              >
                Cancel
              </button>
            </div>
          </div>
        )}

        {/* 5. Filters Card */}
        <Card className="shadow-xs border border-zinc-200 dark:border-zinc-800 rounded-xl" bodyStyle={{ padding: "14px" }}>
          <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-5 gap-3">
            {/* Search Box */}
            <div className="flex flex-col gap-1">
              <span className="font-bold text-zinc-400 uppercase text-[9px]">Search Log</span>
              <div className="relative">
                <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-zinc-400" />
                <input
                  type="text"
                  placeholder="Report No or Type..."
                  value={localSearch}
                  onChange={e => setLocalSearch(e.target.value)}
                  className="pl-9 pr-4 py-2 w-full text-xs rounded-lg border border-zinc-300 dark:border-zinc-700 bg-white dark:bg-zinc-950 text-zinc-800 dark:text-zinc-100 focus:outline-none focus:border-[var(--primary)] transition-all font-semibold h-[34px]"
                />
              </div>
            </div>

            {/* Report Type Filter */}
            <div className="flex flex-col gap-1">
              <span className="font-bold text-zinc-400 uppercase text-[9px]">Report Type</span>
              <Select value={reportType} onChange={val => setReportType(val)} className="w-full font-semibold h-8.5">
                <Select.Option value="All">All Types</Select.Option>
                <Select.Option value="Sales Report">Sales Report</Select.Option>
                <Select.Option value="Store Performance Report">Store Performance</Select.Option>
                <Select.Option value="Product Sales Report">Product Sales</Select.Option>
                <Select.Option value="Inventory Report">Inventory Report</Select.Option>
                <Select.Option value="Rider Performance Report">Rider Performance</Select.Option>
                <Select.Option value="Customer Report">Customer Report</Select.Option>
                <Select.Option value="Finance Report">Finance Report</Select.Option>
              </Select>
            </div>

            {/* Status Filter */}
            <div className="flex flex-col gap-1">
              <span className="font-bold text-zinc-400 uppercase text-[9px]">Queue Status</span>
              <Select value={status} onChange={val => setStatus(val)} className="w-full font-semibold h-8.5">
                <Select.Option value="All">All Statuses</Select.Option>
                <Select.Option value="Generating">Generating</Select.Option>
                <Select.Option value="Completed">Completed</Select.Option>
                <Select.Option value="Failed">Failed</Select.Option>
              </Select>
            </div>

            {/* Generated By Filter */}
            <div className="flex flex-col gap-1">
              <span className="font-bold text-zinc-400 uppercase text-[9px]">Generated By</span>
              <Select value={generatedBy} onChange={val => setGeneratedBy(val)} className="w-full font-semibold h-8.5">
                <Select.Option value="All">All Users</Select.Option>
                {usersList.map(user => (
                  <Select.Option key={user} value={user}>{user}</Select.Option>
                ))}
              </Select>
            </div>

            {/* Date Range Preset Selector */}
            <div className="flex flex-col gap-1">
              <span className="font-bold text-zinc-400 uppercase text-[9px]">Date Interval</span>
              <Select value={dateFilter} onChange={val => setDateFilter(val)} className="w-full font-semibold h-8.5">
                {Object.keys(dateLabels).map(key => (
                  <Select.Option key={key} value={key}>{dateLabels[key]}</Select.Option>
                ))}
              </Select>
            </div>
          </div>

          {/* Custom Datepicker row */}
          {dateFilter === "Custom" && (
            <div className="mt-3 flex items-center gap-2 border-t border-zinc-100 dark:border-zinc-800 pt-3 animate-fade-down">
              <span className="font-bold text-zinc-500 text-[10px] uppercase">Select Custom Range:</span>
              <DatePicker
                placeholder="Start Date"
                value={customRange.start ? dayjs(customRange.start) : null}
                onChange={date => setCustomRange(prev => ({ ...prev, start: date ? date.format("YYYY-MM-DD") : null }))}
              />
              <span className="font-bold text-zinc-400">-</span>
              <DatePicker
                placeholder="End Date"
                value={customRange.end ? dayjs(customRange.end) : null}
                onChange={date => setCustomRange(prev => ({ ...prev, end: date ? date.format("YYYY-MM-DD") : null }))}
              />
              <button
                onClick={() => setCustomRange({ start: null, end: null })}
                className="text-[10px] font-bold text-[var(--primary)] hover:underline cursor-pointer bg-transparent border-0"
              >
                Clear Range
              </button>
            </div>
          )}

          {/* Reset Filters Option */}
          <div className="flex justify-end mt-2">
            <button
              onClick={handleResetFilters}
              className="text-[10px] font-bold p-0 flex items-center gap-1 text-[var(--primary)] hover:underline cursor-pointer bg-transparent border-0"
            >
              Reset Filters
            </button>
          </div>
        </Card>

        {/* 6. Tabs for Logs vs Schedule Loops */}
        <div className="bg-white dark:bg-zinc-900 border border-zinc-200 dark:border-zinc-800 p-4 rounded-xl shadow-xs">
          <Tabs defaultActiveKey="1" className="reports-tabs font-bold">
            <TabPane
              tab={
                <span className="flex items-center gap-1 text-xs">
                  <FileText size={14} className="text-[var(--primary)]" />
                  Generated Reports Log
                </span>
              }
              key="1"
            >
              <div className="space-y-4 pt-2">
                <div className="flex justify-between items-center">
                  <h3 className="font-extrabold text-xs text-zinc-800 dark:text-zinc-150 uppercase tracking-wider">
                    Reports database ledger
                  </h3>
                  <div className="flex items-center gap-2">
                    <button
                      onClick={bulkExportCSV}
                      className="flex items-center gap-1 px-3 py-1.5 text-[9.5px] font-black uppercase rounded-lg bg-[var(--primary)]/10 text-[var(--primary)] hover:bg-[var(--primary)] hover:text-white transition-all duration-200 cursor-pointer shadow-xs"
                    >
                      <Download size={12} />
                      <span>Export List</span>
                    </button>
                    <span className="text-[9px] font-bold text-zinc-450">
                      Showing {tableData.length} of {totalRecords} records
                    </span>
                  </div>
                </div>

                <Table
                  rowSelection={rowSelection}
                  columns={columns}
                  dataSource={tableData}
                  rowKey="_id"
                  loading={loading}
                  onChange={handleTableChange}
                  pagination={false}
                  size="small"
                  bordered
                  className="text-xs scrollbar-thin overflow-x-auto"
                  locale={{
                    emptyText: (
                      <div className="py-8 flex flex-col items-center justify-center text-center">
                        <img
                          src={emptyReportsWebp}
                          alt="No reports illustration"
                          className="w-32 h-32 object-contain mb-3 opacity-60 dark:opacity-40"
                        />
                        <h4 className="font-extrabold text-xs text-zinc-650 dark:text-zinc-350">No reports available.</h4>
                        <p className="text-[10px] text-zinc-400 max-w-[250px] mt-0.5 leading-normal">
                          Get started by generating your first analytics reports compilation task.
                        </p>
                        <button
                          onClick={() => setShowGenerateModal(true)}
                          className="mt-3 px-4 py-2 bg-[var(--primary)] hover:bg-[var(--primary-hover)] text-white font-extrabold text-[10px] uppercase rounded-lg cursor-pointer shadow-md"
                        >
                          Generate Report
                        </button>
                      </div>
                    )
                  }}
                />

                <div className="flex justify-end mt-4">
                  <Pagination
                    current={currentPage}
                    pageSize={pageSize}
                    total={totalRecords}
                    onChange={(page, size) => {
                      setCurrentPage(page);
                      setPageSize(size);
                    }}
                    showSizeChanger
                    pageSizeOptions={["10", "20", "50", "100"]}
                    className="font-semibold text-xs"
                  />
                </div>
              </div>
            </TabPane>

            <TabPane
              tab={
                <span className="flex items-center gap-1 text-xs">
                  <Calendar size={14} className="text-[var(--primary)]" />
                  Scheduled Automated Reports
                </span>
              }
              key="2"
            >
              <div className="space-y-4 pt-2">
                <div className="flex justify-between items-center">
                  <h3 className="font-extrabold text-xs text-zinc-800 dark:text-zinc-150 uppercase tracking-wider">
                    Automated Scheduler Loops
                  </h3>
                  <button
                    onClick={() => {
                      setSelectedSchedule(null);
                      setShowScheduleModal(true);
                    }}
                    className="flex items-center justify-center gap-1 px-3 py-1.5 bg-[var(--primary)] hover:bg-[var(--primary-hover)] text-white rounded-lg shadow-sm font-extrabold transition-all duration-200 cursor-pointer text-[9.5px] uppercase"
                  >
                    <Plus size={12} />
                    <span>Create Schedule</span>
                  </button>
                </div>

                <Table
                  columns={scheduleColumns}
                  dataSource={schedulesTableData}
                  rowKey="_id"
                  loading={loading}
                  pagination={false}
                  size="small"
                  bordered
                  className="text-xs scrollbar-thin overflow-x-auto"
                  onRow={(record) => ({
                    onClick: (event) => {
                      // Avoid drawer opening when clicking switches or buttons in actions
                      if (event.target.tagName !== "BUTTON" && !event.target.closest("button") && !event.target.closest(".ant-switch")) {
                        handleRowClick(record);
                      }
                    }
                  })}
                  locale={{
                    emptyText: (
                      <div className="py-8 flex flex-col items-center justify-center">
                        <Empty image={Empty.PRESENTED_IMAGE_SIMPLE} description="No automated schedules." />
                        <button
                          onClick={() => {
                            setSelectedSchedule(null);
                            setShowScheduleModal(true);
                          }}
                          className="mt-2 px-4 py-1.5 bg-[var(--primary)] text-white font-extrabold text-[10px] uppercase rounded-lg cursor-pointer"
                        >
                          Configure Schedule
                        </button>
                      </div>
                    )
                  }}
                />
              </div>
            </TabPane>
          </Tabs>
        </div>

        {/* 7. Modals Mounting */}
        <GenerateReportModal
          visible={showGenerateModal}
          onClose={() => setShowGenerateModal(false)}
          onGenerate={generateReport}
        />

        <ReportDetailsModal
          visible={showDetailsModal}
          report={selectedReport}
          onClose={() => setShowDetailsModal(false)}
          onDownload={downloadReport}
          onRegenerate={retryReport}
        />

        <ScheduleReportModal
          visible={showScheduleModal}
          schedule={selectedSchedule}
          onClose={() => setShowScheduleModal(false)}
          onSave={(id, config) => {
            if (id) {
              return updateSchedule(id, config);
            } else {
              return scheduleReport(config);
            }
          }}
        />

        <ScheduleDetailsDrawer
          visible={showScheduleDrawer}
          schedule={selectedSchedule}
          onClose={() => setShowScheduleDrawer(false)}
          onEdit={(sch) => {
            setSelectedSchedule(sch);
            setShowScheduleModal(true);
          }}
          onToggleActive={toggleScheduleActive}
        />

        <DeleteConfirmationModal
          visible={showDeleteModal}
          title="Delete Generated Report"
          message="Are you sure you want to delete this generated report file log? This action is permanent and cannot be undone."
          onConfirm={() => {
            if (Array.isArray(itemToDelete)) {
              // Bulk delete
              bulkDeleteSelected();
            } else {
              // Single delete
              deleteReport(itemToDelete);
            }
            setShowDeleteModal(false);
            setItemToDelete(null);
          }}
          onCancel={() => {
            setShowDeleteModal(false);
            setItemToDelete(null);
          }}
        />

        <DeleteConfirmationModal
          visible={showDeleteScheduleModal}
          title="Delete Report Schedule"
          message="Are you sure you want to delete this report schedule? Automated background generation loops for this category will stop immediately."
          onConfirm={() => {
            deleteSchedule(itemToDelete);
            setShowDeleteScheduleModal(false);
            setItemToDelete(null);
          }}
          onCancel={() => {
            setShowDeleteScheduleModal(false);
            setItemToDelete(null);
          }}
        />

      </div>
    </ConfigProvider>
  );
}
