import React, { useState } from 'react';
import { 
  ArrowLeft, BarChart2, Calendar, RefreshCw, Download, Printer, 
  TrendingUp, TrendingDown, Wallet, ShoppingBag, ShieldCheck, Lock, X 
} from 'lucide-react';

export default function RevenueReportDetails({ onBack }) {
  const [isDrawerOpen, setIsDrawerOpen] = useState(false);

  const toggleDrawer = () => {
    setIsDrawerOpen(!isDrawerOpen);
  };

  return (
    <div className="bg-zinc-50 dark:bg-zinc-955 min-h-screen animate-fade-in pb-12">
      {/* Top Navigation Anchor */}
      <header className="w-full top-0 sticky z-40 bg-white dark:bg-zinc-950 border-b border-zinc-200 dark:border-zinc-800 shadow-sm">
        <div className="flex justify-between items-center px-4 py-2.5 w-full max-w-7xl mx-auto">
          <div className="flex items-center gap-2">
            <button 
              onClick={onBack}
              className="p-1 rounded-full hover:bg-zinc-100 dark:hover:bg-zinc-800 transition-colors cursor-pointer active:scale-90"
            >
              <ArrowLeft className="text-[var(--primary)]" size={14} />
            </button>
            <div className="flex items-center gap-1.5">
              <BarChart2 className="text-[var(--primary)]" size={18} />
              <h1 className="text-sm font-bold text-[var(--primary)] hidden sm:block">Franchise Analytics</h1>
              <h1 className="text-xs font-bold text-[var(--primary)] sm:hidden">Analytics</h1>
            </div>
          </div>
          <div className="flex items-center gap-3">
            <div className="text-right hidden md:block">
              <p className="text-[9px] font-bold text-black/55 dark:text-white/55 uppercase tracking-wider mb-0.5">Report Generated By</p>
              <p className="text-xs font-bold text-black dark:text-white">Super Admin</p>
            </div>
            <div className="w-6 h-6 rounded-full bg-[var(--primary)]/10 dark:bg-[var(--primary)]/20 flex items-center justify-center text-[var(--primary)] font-bold border border-[var(--primary)]/20 shadow-sm shrink-0 text-[10px]">
              SA
            </div>
          </div>
        </div>
      </header>

      <main className="max-w-7xl mx-auto p-3 md:p-4 space-y-4">
        
        {/* Header Info & Controls */}
        <div className="flex flex-col lg:flex-row justify-between items-start lg:items-center gap-3">
          <div>
            <p className="text-[9px] font-bold text-[var(--primary)] uppercase tracking-widest mb-0.5">Detailed Analysis</p>
            <h2 className="text-base font-bold text-black dark:text-white">Revenue Breakdown Report</h2>
            <div className="flex flex-wrap items-center gap-2 mt-1.5">
              <span className="flex items-center gap-1.5 bg-white dark:bg-zinc-900 border border-zinc-200 dark:border-zinc-800 shadow-sm px-2.5 py-1 rounded-lg text-black/70 dark:text-white/70 text-xs font-semibold">
                <Calendar size={12} className="text-[var(--primary)]" />
                Oct 01 - Oct 31, 2023
              </span>
              <span className="flex items-center gap-1.5 bg-white dark:bg-zinc-900 border border-zinc-200 dark:border-zinc-800 shadow-sm px-2.5 py-1 rounded-lg text-black/70 dark:text-white/70 text-xs font-semibold">
                <RefreshCw size={12} className="text-[var(--primary)]" />
                Last Sync: 5 mins ago
              </span>
            </div>
          </div>
          <div className="flex gap-2 w-full lg:w-auto shrink-0">
            <button className="flex-1 lg:flex-none flex items-center justify-center gap-1.5 px-3 py-1.5 rounded-lg border border-zinc-200 dark:border-zinc-700 bg-white dark:bg-zinc-900 text-black/70 dark:text-white/70 hover:bg-zinc-50 dark:hover:bg-zinc-800 transition-colors font-bold text-xs shadow-sm">
              <Download size={14} />
              <span>Export PDF</span>
            </button>
            <button className="flex-1 lg:flex-none flex items-center justify-center gap-1.5 px-3 py-1.5 rounded-lg bg-[var(--primary)] text-white hover:brightness-110 active:scale-95 transition-all font-bold text-xs shadow-md shadow-[var(--primary)]/20">
              <Printer size={14} />
              <span>Print Report</span>
            </button>
          </div>
        </div>

        {/* Bento Grid Layout */}
        <div className="grid grid-cols-12 gap-4">
          
          {/* 1. Revenue Overview */}
          <div className="col-span-12 xl:col-span-8 bg-white dark:bg-zinc-900 border border-zinc-200 dark:border-zinc-800 rounded-xl p-3.5 shadow-sm hover:shadow-md transition-shadow relative overflow-hidden group">
            <div className="flex justify-between items-start mb-4">
              <div>
                <h3 className="text-xs font-bold text-black dark:text-white mb-0.5">Revenue Overview</h3>
                <p className="text-[10px] font-semibold text-black/50 dark:text-white/50">Gross Achievement vs Target</p>
              </div>
              <div className="text-right">
                <span className="text-lg font-black text-[var(--primary)]">92%</span>
                <p className="text-[9px] font-bold text-black/50 dark:text-white/50 uppercase mt-0.5 tracking-wider">Of Monthly Target</p>
              </div>
            </div>
            
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 mt-3">
              <div className="p-2.5 rounded-lg bg-zinc-50 dark:bg-zinc-950/50 border border-zinc-100 dark:border-zinc-800/50">
                <p className="text-[9px] font-bold text-black/50 dark:text-white/50 mb-1.5 uppercase tracking-wider">Gross Revenue</p>
                <p className="text-sm font-black text-black dark:text-white">$482,900.00</p>
                <div className="flex items-center gap-1 text-emerald-600 dark:text-emerald-500 mt-2 font-bold text-xs">
                  <TrendingUp size={12} />
                  <span>+12.4% vs Prev Month</span>
                </div>
              </div>
              <div className="p-2.5 rounded-lg bg-zinc-50 dark:bg-zinc-955 border border-zinc-100 dark:border-zinc-800/50">
                <p className="text-[9px] font-bold text-black/50 dark:text-white/50 mb-1.5 uppercase tracking-wider">Net Revenue</p>
                <p className="text-sm font-black text-black dark:text-white">$444,268.00</p>
                <div className="flex items-center gap-1 text-rose-600 dark:text-rose-500 mt-2 font-bold text-xs">
                  <TrendingDown size={12} />
                  <span>-2.1% from Gross Gap</span>
                </div>
              </div>
            </div>
            
            <div className="mt-4">
              <div className="w-full h-1.5 bg-zinc-100 dark:bg-zinc-800 rounded-full overflow-hidden relative">
                <div className="absolute top-0 left-0 h-full bg-[var(--primary)] rounded-full transition-all duration-1000" style={{ width: '92%' }}></div>
              </div>
              <div className="flex justify-between mt-1.5">
                <span className="text-[10px] font-bold text-black/50 dark:text-white/50">$0</span>
                <span className="text-[10px] font-bold text-black/50 dark:text-white/50">Target: $525,000</span>
              </div>
            </div>
          </div>

          {/* 2. Profitability Analysis */}
          <div className="col-span-12 md:col-span-6 xl:col-span-4 bg-[var(--primary)] text-white rounded-xl p-3.5 shadow-md shadow-[var(--primary)]/20 flex flex-col justify-between relative overflow-hidden">
            <div className="absolute -right-6 -top-6 opacity-10 pointer-events-none">
              <Wallet size={100} />
            </div>
            <div className="relative z-10">
              <h3 className="text-xs font-bold mb-0.5">Profitability Analysis</h3>
              <p className="text-[10px] font-semibold text-white/85">Final margin after all deductions</p>
            </div>
            
            <div className="my-4 relative z-10">
              <div className="flex items-end gap-1.5">
                <span className="text-xl font-black leading-none">18.5%</span>
                <span className="text-xs font-bold mb-0.5 opacity-90">Margin</span>
              </div>
              <p className="text-[10px] font-semibold mt-1.5 text-white/90">Net profit of $82,190.00 this month</p>
            </div>
            
            <div className="space-y-2 relative z-10">
              <div className="flex justify-between items-center py-1.5 border-b border-white/20 text-xs">
                <span className="font-bold text-white/90">Operating Costs</span>
                <span className="font-mono font-bold">$242,000.00</span>
              </div>
              <div className="flex justify-between items-center py-1.5 border-b border-white/20 text-xs">
                <span className="font-bold text-white/90">Commissions</span>
                <span className="font-mono font-bold">$120,078.00</span>
              </div>
              <div className="flex justify-between items-center py-1.5 text-xs">
                <span className="font-bold text-white/90">Net Profit</span>
                <span className="font-mono text-sm font-black">$82,190.00</span>
              </div>
            </div>
          </div>

          {/* 3. Sales Breakdown */}
          <div className="col-span-12 md:col-span-6 xl:col-span-4 bg-white dark:bg-zinc-900 border border-zinc-200 dark:border-zinc-800 rounded-xl p-3.5 shadow-sm flex flex-col">
            <h3 className="text-xs font-bold text-black dark:text-white mb-3.5">Sales Breakdown</h3>
            <div className="space-y-3.5 flex-1">
              <div className="space-y-1">
                <div className="flex justify-between text-xs font-bold">
                  <span className="text-black/70 dark:text-white/70">Online Store</span>
                  <span className="text-black dark:text-white">52%</span>
                </div>
                <div className="w-full h-1.5 bg-zinc-100 dark:bg-zinc-800 rounded-full overflow-hidden">
                  <div className="h-full bg-[var(--primary)] rounded-full" style={{ width: '52%' }}></div>
                </div>
              </div>
              <div className="space-y-1">
                <div className="flex justify-between text-xs font-bold">
                  <span className="text-black/70 dark:text-white/70">In-Store Purchase</span>
                  <span className="text-black dark:text-white">34%</span>
                </div>
                <div className="w-full h-1.5 bg-zinc-100 dark:bg-zinc-800 rounded-full overflow-hidden">
                  <div className="h-full bg-zinc-500 dark:bg-zinc-400 rounded-full" style={{ width: '34%' }}></div>
                </div>
              </div>
              <div className="space-y-1">
                <div className="flex justify-between text-xs font-bold">
                  <span className="text-black/70 dark:text-white/70">Third-Party Delivery</span>
                  <span className="text-black dark:text-white">14%</span>
                </div>
                <div className="w-full h-1.5 bg-zinc-100 dark:bg-zinc-800 rounded-full overflow-hidden">
                  <div className="h-full bg-orange-500 rounded-full" style={{ width: '14%' }}></div>
                </div>
              </div>
            </div>
            
            <div className="mt-4 pt-3 border-t border-zinc-200 dark:border-zinc-800">
              <div className="flex items-center gap-3">
                <div className="p-1.5 bg-zinc-50 dark:bg-zinc-950/50 rounded-lg border border-zinc-100 dark:border-zinc-800/50 shrink-0">
                  <ShoppingBag className="text-[var(--primary)]" size={14} />
                </div>
                <div>
                  <p className="font-mono text-xs font-bold text-black dark:text-white">4,821 Orders</p>
                  <p className="text-[10px] font-semibold text-black/50 dark:text-white/50 mt-0.5">Avg. Order Value: $100.16</p>
                </div>
              </div>
            </div>
          </div>

          {/* 4. Tax & Fees Details */}
          <div className="col-span-12 md:col-span-6 xl:col-span-4 bg-white dark:bg-zinc-900 border border-zinc-200 dark:border-zinc-800 rounded-xl p-3.5 shadow-sm overflow-hidden flex flex-col">
            <h3 className="text-xs font-bold text-black dark:text-white mb-3">Tax & Fees</h3>
            <div className="overflow-x-auto flex-1">
              <table className="w-full">
                <thead className="border-b border-zinc-200 dark:border-zinc-800">
                  <tr>
                    <th className="text-left text-[9px] font-bold text-black/50 dark:text-white/50 uppercase tracking-wider pb-1.5">Type</th>
                    <th className="text-right text-[9px] font-bold text-black/50 dark:text-white/50 uppercase tracking-wider pb-1.5">Amount</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-zinc-100 dark:divide-zinc-800/50">
                  <tr>
                    <td className="py-2 text-xs font-bold text-black dark:text-white">GST (Total)</td>
                    <td className="py-2 font-mono text-xs font-bold text-right text-black dark:text-white">$43,461.00</td>
                  </tr>
                  <tr>
                    <td className="py-1.5 text-xs font-semibold text-black/50 dark:text-white/50 pl-2">CGST (9%)</td>
                    <td className="py-1.5 font-mono text-xs font-semibold text-right text-black/50 dark:text-white/50">$21,730.50</td>
                  </tr>
                  <tr>
                    <td className="py-1.5 text-xs font-semibold text-black/50 dark:text-white/50 pl-2">SGST (9%)</td>
                    <td className="py-1.5 font-mono text-xs font-semibold text-right text-black/50 dark:text-white/50">$21,730.50</td>
                  </tr>
                  <tr>
                    <td className="py-2 text-xs font-bold text-black dark:text-white">Service Charge</td>
                    <td className="py-2 font-mono text-xs font-bold text-right text-black dark:text-white">$12,072.00</td>
                  </tr>
                </tbody>
                <tfoot className="border-t border-zinc-200 dark:border-zinc-800">
                  <tr>
                    <td className="py-2 text-xs font-black text-black dark:text-white">Total Deductions</td>
                    <td className="py-2 font-mono text-sm font-black text-right text-black dark:text-white">$55,533.00</td>
                  </tr>
                </tfoot>
              </table>
            </div>
          </div>

          {/* 5. Refund Analysis */}
          <div className="col-span-12 md:col-span-6 xl:col-span-4 bg-white dark:bg-zinc-900 border border-zinc-200 dark:border-zinc-800 rounded-xl p-3.5 shadow-sm flex flex-col">
            <div className="flex justify-between items-center mb-3">
              <h3 className="text-xs font-bold text-black dark:text-white">Refund Analysis</h3>
              <span className="bg-rose-50 dark:bg-rose-900/20 text-rose-600 dark:text-rose-400 px-1.5 py-0.5 rounded text-[9px] font-bold border border-rose-200 dark:border-rose-800/30 shadow-sm">
                High Impact
              </span>
            </div>
            
            <div className="mb-3.5 p-2.5 bg-rose-50 dark:bg-rose-955 rounded-lg border border-rose-100 dark:border-rose-900/30">
              <p className="text-[9px] font-bold text-rose-600 dark:text-rose-500 uppercase tracking-widest mb-0.5">Net Impact</p>
              <p className="text-sm font-black text-rose-700 dark:text-rose-400">-$18,240.00</p>
              <p className="text-[10px] font-semibold text-rose-600 dark:text-rose-500 opacity-80 mt-1">Total of 214 refund events</p>
            </div>
            
            <div className="space-y-2 flex-1">
              <p className="text-[9px] font-bold text-black/50 dark:text-white/50 uppercase tracking-wider">Top Refund Reasons</p>
              <div className="flex items-center justify-between text-xs">
                <div className="flex items-center gap-2">
                  <div className="w-2 h-2 rounded-full bg-rose-500"></div>
                  <span className="font-bold text-black/70 dark:text-white/70">Order Cancellation</span>
                </div>
                <span className="font-mono font-bold text-black dark:text-white">48%</span>
              </div>
              <div className="flex items-center justify-between text-xs">
                <div className="flex items-center gap-2">
                  <div className="w-2 h-2 rounded-full bg-orange-500"></div>
                  <span className="font-bold text-black/70 dark:text-white/70">Damaged Goods</span>
                </div>
                <span className="font-mono font-bold text-black dark:text-white">32%</span>
              </div>
              <div className="flex items-center justify-between text-xs">
                <div className="flex items-center gap-2">
                  <div className="w-2 h-2 rounded-full bg-amber-500"></div>
                  <span className="font-bold text-black/70 dark:text-white/70">Incorrect Item</span>
                </div>
                <span className="font-mono font-bold text-black dark:text-white">20%</span>
              </div>
            </div>
            
            <button 
              onClick={toggleDrawer}
              className="w-full mt-4 py-1.5 rounded-lg border-2 border-zinc-200 dark:border-zinc-700 text-black/70 dark:text-white/70 font-bold text-xs hover:bg-zinc-50 dark:hover:bg-zinc-800 transition-colors active:scale-[0.98]"
            >
              View Full Refund Audit
            </button>
          </div>

        </div>

        {/* Audit Trail Footer */}
        <footer className="mt-4 pt-4 border-t border-zinc-200 dark:border-zinc-800 flex flex-col md:flex-row justify-between items-center gap-4 text-xs font-semibold">
          <div className="flex flex-wrap justify-center md:justify-start items-center gap-4">
            <div className="flex items-center gap-1.5 text-black/50 dark:text-white/50">
              <ShieldCheck size={14} />
              <p>Authenticated Report</p>
            </div>
            <div className="flex items-center gap-1.5 text-black/50 dark:text-white/50">
              <Lock size={14} />
              <p>SHA-256 Encrypted</p>
            </div>
          </div>
          <div className="flex items-center gap-3 text-center md:text-right">
            <p className="text-black/50 dark:text-white/50">System Version: <span className="font-bold text-black dark:text-white">v2.4.1</span></p>
            <div className="h-3.5 w-px bg-zinc-350 dark:bg-zinc-700"></div>
            <p className="text-black/50 dark:text-white/50">Instance: <span className="font-bold text-black dark:text-white">Node-04_Production</span></p>
          </div>
        </footer>
      </main>

      {/* Detailed Insights Floating Drawer (Audit Logs) */}
      <div 
        className={`fixed right-0 top-0 h-full w-full sm:w-[360px] bg-white dark:bg-zinc-950 border-l border-zinc-200 dark:border-zinc-800 shadow-2xl z-[100] transform transition-transform duration-300 flex flex-col ${isDrawerOpen ? 'translate-x-0' : 'translate-x-full'}`}
      >
        <div className="p-3.5 flex flex-col h-full">
          <div className="flex justify-between items-center mb-4">
            <h4 className="text-sm font-bold text-black dark:text-white">Audit Log Details</h4>
            <button 
              className="p-1 rounded-full hover:bg-zinc-100 dark:hover:bg-zinc-800 text-black/50 dark:text-white/50 transition-colors"
              onClick={toggleDrawer}
            >
              <X size={14} />
            </button>
          </div>
          
          <div className="space-y-3.5 overflow-y-auto custom-scrollbar flex-1 pr-1.5">
            
            <div className="p-2.5 rounded-lg bg-zinc-50 dark:bg-zinc-900 border border-zinc-200 dark:border-zinc-800">
              <div className="flex justify-between mb-2 text-[10px] font-bold">
                <span className="text-[9px] font-black text-[var(--primary)] uppercase tracking-wider bg-[var(--primary)]/10 px-1.5 py-0.5 rounded">Action</span>
                <span className="text-black/50 dark:text-white/50">10:45 AM</span>
              </div>
              <p className="text-xs font-bold text-black dark:text-white">Manual Adjustment Approved</p>
              <p className="text-[11px] text-black/70 dark:text-white/70 mt-1.5 font-semibold leading-relaxed">Super Admin adjusted Refund #4021 from 'Pending' to 'Settled'.</p>
            </div>
            
            <div className="p-2.5 rounded-lg bg-zinc-50 dark:bg-zinc-900 border border-zinc-200 dark:border-zinc-800 opacity-70 hover:opacity-100 transition-opacity">
              <div className="flex justify-between mb-2 text-[10px] font-bold">
                <span className="text-[9px] font-black text-amber-600 uppercase tracking-wider bg-amber-500/10 px-1.5 py-0.5 rounded">Sync</span>
                <span className="text-black/50 dark:text-white/50">10:40 AM</span>
              </div>
              <p className="text-xs font-bold text-black dark:text-white">POS Data Ingested</p>
              <p className="text-[11px] text-black/70 dark:text-white/70 mt-1.5 font-semibold leading-relaxed">Data from 42 outlets successfully synced with central repository.</p>
            </div>

            <div className="p-2.5 rounded-lg bg-zinc-50 dark:bg-zinc-900 border border-zinc-200 dark:border-zinc-800 opacity-70 hover:opacity-100 transition-opacity">
              <div className="flex justify-between mb-2 text-[10px] font-bold">
                <span className="text-[9px] font-black text-rose-600 uppercase tracking-wider bg-rose-500/10 px-1.5 py-0.5 rounded">Alert</span>
                <span className="text-black/50 dark:text-white/50">09:15 AM</span>
              </div>
              <p className="text-xs font-bold text-black dark:text-white">Refund Spike Detected</p>
              <p className="text-[11px] text-black/70 dark:text-white/70 mt-1.5 font-semibold leading-relaxed">Unusual volume of order cancellations detected in North Region.</p>
            </div>

          </div>
          
          <div className="pt-3.5 mt-3 border-t border-zinc-200 dark:border-zinc-800">
            <button className="w-full py-1.5 bg-[var(--primary)] text-white rounded-lg font-bold text-xs shadow-md hover:brightness-110 active:scale-[0.98] transition-all">
              Verify Chain of Custody
            </button>
          </div>
        </div>
      </div>
      
      {/* Drawer Overlay */}
      {isDrawerOpen && (
        <div 
          className="fixed inset-0 bg-black/40 backdrop-blur-sm z-[90] transition-opacity"
          onClick={toggleDrawer}
        ></div>
      )}

    </div>
  );
}
