import React, { useState } from "react";
import { Modal, Tabs, Card, Tag, Button, Progress, Divider } from "antd";
import { 
  FileText, Download, RefreshCw, Calendar, Store, Clock, Database, 
  ExternalLink, User, Hash, Info, CheckCircle2, AlertTriangle, Play 
} from "lucide-react";

export default function ReportDetailsModal({ visible, report, onClose, onDownload, onRegenerate }) {
  const [activeTab, setActiveTab] = useState("1");
  const [regenerating, setRegenerating] = useState(false);

  if (!report) return null;

  const handleRegenerate = async () => {
    setRegenerating(true);
    try {
      await onRegenerate(report._id);
      setActiveTab("1");
    } finally {
      setRegenerating(false);
    }
  };

  const statusColors = {
    Completed: { color: "green", text: "Completed" },
    Generating: { color: "orange", text: "Generating" },
    Failed: { color: "red", text: "Failed" }
  };

  const statusObj = statusColors[report.status] || { color: "default", text: report.status };

  const tabsItems = [
    {
      key: "1",
      label: "Overview",
      children: (
        <div className="space-y-4 pt-2">
          <div className="grid grid-cols-2 sm:grid-cols-4 gap-4">
            <Card className="bg-zinc-50 dark:bg-zinc-950/40 border border-zinc-150 dark:border-zinc-800 p-2.5 rounded-2xl flex flex-col justify-between" bodyStyle={{ padding: 0 }}>
              <span className="text-[9px] font-extrabold uppercase text-zinc-400 block mb-0.5">Report Number</span>
              <span className="text-xs font-black text-slate-800 dark:text-white flex items-center gap-1">
                <Hash size={12} className="text-zinc-400" />
                {report.reportNumber}
              </span>
            </Card>

            <Card className="bg-zinc-50 dark:bg-zinc-950/40 border border-zinc-150 dark:border-zinc-800 p-2.5 rounded-2xl flex flex-col justify-between" bodyStyle={{ padding: 0 }}>
              <span className="text-[9px] font-extrabold uppercase text-zinc-400 block mb-0.5">Report Type</span>
              <span className="text-xs font-black text-slate-800 dark:text-white truncate flex items-center gap-1">
                <FileText size={12} className="text-zinc-400 shrink-0" />
                {report.reportType}
              </span>
            </Card>

            <Card className="bg-zinc-50 dark:bg-zinc-950/40 border border-zinc-150 dark:border-zinc-800 p-2.5 rounded-2xl flex flex-col justify-between" bodyStyle={{ padding: 0 }}>
              <span className="text-[9px] font-extrabold uppercase text-zinc-400 block mb-0.5">Generated By</span>
              <span className="text-xs font-black text-slate-800 dark:text-white flex items-center gap-1">
                <User size={12} className="text-zinc-400" />
                {report.generatedBy}
              </span>
            </Card>

            <Card className="bg-zinc-50 dark:bg-zinc-950/40 border border-zinc-150 dark:border-zinc-800 p-2.5 rounded-2xl flex flex-col justify-between" bodyStyle={{ padding: 0 }}>
              <span className="text-[9px] font-extrabold uppercase text-zinc-400 block mb-0.5">Job Status</span>
              <Tag color={statusObj.color} className="font-extrabold text-[10px] uppercase border-0 px-2 py-0.5 rounded mt-0.5 inline-block w-fit">
                {statusObj.text}
              </Tag>
            </Card>
          </div>

          <div className="grid grid-cols-2 sm:grid-cols-4 gap-4">
            <Card className="bg-zinc-50 dark:bg-zinc-950/40 border border-zinc-150 dark:border-zinc-800 p-2.5 rounded-2xl flex flex-col justify-between" bodyStyle={{ padding: 0 }}>
              <span className="text-[9px] font-extrabold uppercase text-zinc-400 block mb-0.5">Compile Duration</span>
              <span className="text-xs font-black text-slate-800 dark:text-white flex items-center gap-1">
                <Clock size={12} className="text-zinc-400" />
                {report.duration}
              </span>
            </Card>

            <Card className="bg-zinc-50 dark:bg-zinc-950/40 border border-zinc-150 dark:border-zinc-800 p-2.5 rounded-2xl flex flex-col justify-between" bodyStyle={{ padding: 0 }}>
              <span className="text-[9px] font-extrabold uppercase text-zinc-400 block mb-0.5">File Size</span>
              <span className="text-xs font-black text-slate-800 dark:text-white">
                {report.fileSize}
              </span>
            </Card>

            <Card className="bg-zinc-50 dark:bg-zinc-950/40 border border-zinc-150 dark:border-zinc-800 p-2.5 rounded-2xl flex flex-col justify-between" bodyStyle={{ padding: 0 }}>
              <span className="text-[9px] font-extrabold uppercase text-zinc-400 block mb-0.5">Created At</span>
              <span className="text-xs font-black text-slate-800 dark:text-white">
                {new Date(report.createdAt).toLocaleString("en-IN", { day: "2-digit", month: "short", hour: "2-digit", minute: "2-digit" })}
              </span>
            </Card>

            <Card className="bg-zinc-50 dark:bg-zinc-950/40 border border-zinc-150 dark:border-zinc-800 p-2.5 rounded-2xl flex flex-col justify-between" bodyStyle={{ padding: 0 }}>
              <span className="text-[9px] font-extrabold uppercase text-zinc-400 block mb-0.5">Downloads Count</span>
              <span className="text-xs font-black text-slate-800 dark:text-white">
                {report.downloadCount || 0} times
              </span>
            </Card>
          </div>

          {report.status === "Generating" && (
            <div className="p-4 bg-orange-500/5 rounded-2xl border border-orange-500/15 flex items-center gap-3">
              <RefreshCw size={20} className="text-orange-500 animate-spin shrink-0" />
              <div className="flex-1">
                <span className="text-xs font-bold text-orange-700 dark:text-orange-400 block">Compiling report in background...</span>
                <Progress percent={60} strokeColor="var(--secondary)" size="small" showInfo={false} className="mt-1" />
              </div>
            </div>
          )}

          {report.status === "Failed" && (
            <div className="p-4 bg-rose-500/5 rounded-2xl border border-rose-500/15 flex items-start gap-3">
              <AlertTriangle size={20} className="text-rose-500 shrink-0 mt-0.5" />
              <div>
                <span className="text-xs font-bold text-rose-700 dark:text-rose-400 block">Report Generation Failed</span>
                <p className="text-[10px] text-zinc-500 mt-1">
                  The background process failed due to database query timeout. You can trigger a regenerations task to query the records again.
                </p>
              </div>
            </div>
          )}
        </div>
      )
    },
    {
      key: "2",
      label: "Filters Used",
      children: (
        <div className="space-y-4 pt-2 text-xs">
          <div className="p-4 bg-zinc-50 dark:bg-zinc-950/40 border border-zinc-150 dark:border-zinc-800 rounded-2xl space-y-3">
            <div className="flex items-center gap-2">
              <Calendar size={14} className="text-[var(--primary)]" />
              <span className="font-bold text-zinc-800 dark:text-zinc-200">Date Range Filter:</span>
              <span className="font-semibold text-zinc-500">{report.startDate} to {report.endDate}</span>
            </div>

            <div className="flex items-center gap-2">
              <Store size={14} className="text-[var(--primary)]" />
              <span className="font-bold text-zinc-800 dark:text-zinc-200">Store Filter:</span>
              <span className="font-semibold text-zinc-500">{report.stores}</span>
            </div>

            <div className="flex items-center gap-2">
              <FileText size={14} className="text-[var(--primary)]" />
              <span className="font-bold text-zinc-800 dark:text-zinc-200">Selected Format:</span>
              <Tag color="blue" className="font-bold text-[9px] uppercase">{report.format}</Tag>
            </div>

            <Divider className="my-2" />

            <div className="space-y-1">
              <span className="font-bold text-zinc-800 dark:text-zinc-200 block mb-1">Additional Parameters:</span>
              <div className="grid grid-cols-2 gap-2 text-[10px] font-semibold text-zinc-500">
                <div>Include Graph Visuals: {report.includeCharts ? "Yes" : "No"}</div>
                <div>Include Overview Summary: {report.includeSummary ? "Yes" : "No"}</div>
                <div>Trigger SMTP Dispatch: {report.emailRecipients?.length > 0 ? "Yes" : "No"}</div>
                <div>Auto-archiving active: Yes</div>
              </div>
            </div>
          </div>
        </div>
      )
    },
    {
      key: "3",
      label: "File Information",
      children: (
        <div className="space-y-4 pt-2 text-xs">
          <div className="p-4 bg-zinc-50 dark:bg-zinc-950/40 border border-zinc-150 dark:border-zinc-800 rounded-2xl space-y-3">
            <div className="flex justify-between items-center pb-2 border-b border-zinc-200 dark:border-zinc-850">
              <span className="font-bold text-zinc-800 dark:text-zinc-200">File URL (S3 Cloud Storage):</span>
              {report.fileUrl ? (
                <a href={report.fileUrl} target="_blank" rel="noreferrer" className="text-[var(--primary)] font-bold flex items-center gap-0.5 hover:underline">
                  Open link <ExternalLink size={10} />
                </a>
              ) : (
                <span className="text-zinc-400 italic">Not generated</span>
              )}
            </div>
            
            {report.fileUrl && (
              <div className="text-[10px] font-mono text-zinc-450 truncate bg-white dark:bg-zinc-900 border border-zinc-100 dark:border-zinc-800 p-2 rounded-lg">
                {report.fileUrl}
              </div>
            )}

            <div className="grid grid-cols-2 gap-4 pt-1">
              <div>
                <span className="text-[9px] font-extrabold uppercase text-zinc-400 block mb-0.5">BullMQ Job ID</span>
                <span className="font-mono text-xs font-bold text-slate-800 dark:text-white flex items-center gap-1">
                  <Database size={12} className="text-zinc-400" />
                  {report.jobId}
                </span>
              </div>
              <div>
                <span className="text-[9px] font-extrabold uppercase text-zinc-400 block mb-0.5">File Format Extension</span>
                <span className="font-bold text-slate-800 dark:text-white">
                  {report.format} Document
                </span>
              </div>
            </div>
          </div>
        </div>
      )
    },
    {
      key: "4",
      label: "Document Preview",
      children: (
        <div className="pt-2">
          {report.status === "Completed" ? (
            <div className="border border-zinc-200 dark:border-zinc-800 rounded-2xl overflow-hidden shadow-inner bg-zinc-50 p-4 min-h-[320px] flex flex-col justify-between">
              {/* Simulated PDF report mockup */}
              <div className="space-y-4 bg-white dark:bg-zinc-900 border border-zinc-150 dark:border-zinc-800 p-6 rounded-xl text-xs font-semibold text-zinc-700 dark:text-zinc-300">
                <div className="flex justify-between items-start pb-4 border-b border-zinc-100 dark:border-zinc-800">
                  <div>
                    <h3 className="font-black text-sm text-slate-900 dark:text-white">PAPA VEG PIZZA</h3>
                    <p className="text-[9px] text-zinc-400">Franchise Analytics & Reporting System</p>
                  </div>
                  <div className="text-right">
                    <span className="font-bold text-zinc-800 dark:text-zinc-200 block">{report.reportNumber}</span>
                    <span className="text-[9px] text-zinc-450 block">Date Range: {report.startDate} to {report.endDate}</span>
                  </div>
                </div>

                <div className="space-y-2">
                  <h4 className="font-bold text-slate-800 dark:text-white text-xs uppercase tracking-wide">Report Scope: {report.reportType}</h4>
                  <p className="text-[10px] text-zinc-450 leading-relaxed">
                    This document summarizes Pizza franchise metrics compiled from active databases. It covers order completions, raw inventory depletion cycles, and delivery partner dispatch logs.
                  </p>
                </div>

                <div className="grid grid-cols-3 gap-2 border-t border-b border-zinc-100 dark:border-zinc-800 py-3 my-2 text-center">
                  <div>
                    <span className="text-[9px] font-extrabold uppercase text-zinc-400 block">Total Revenue</span>
                    <span className="font-black text-slate-800 dark:text-white text-xs">₹12,45,690</span>
                  </div>
                  <div>
                    <span className="text-[9px] font-extrabold uppercase text-zinc-400 block">Orders Handled</span>
                    <span className="font-black text-slate-800 dark:text-white text-xs">1,842 orders</span>
                  </div>
                  <div>
                    <span className="text-[9px] font-extrabold uppercase text-zinc-400 block">Avg Order Value</span>
                    <span className="font-black text-slate-800 dark:text-white text-xs">₹676.00</span>
                  </div>
                </div>

                <div className="text-[9px] text-zinc-400 italic text-center pt-2">
                  *This is a digital preview. Click download to fetch the complete full-resolution {report.format} document.
                </div>
              </div>

              <div className="flex justify-center mt-4">
                <Button 
                  type="primary" 
                  onClick={() => onDownload(report._id)}
                  className="bg-[var(--primary)] border-[var(--primary)] hover:bg-[var(--primary-hover)] text-white font-bold rounded-xl h-10 px-6 flex items-center gap-1.5"
                >
                  <Download size={14} />
                  <span>Download Full Report</span>
                </Button>
              </div>
            </div>
          ) : (
            <div className="border border-zinc-200 dark:border-zinc-800 rounded-2xl bg-zinc-50 dark:bg-zinc-950/40 p-12 text-center min-h-[300px] flex flex-col items-center justify-center">
              <Info size={28} className="text-zinc-400 mb-2" />
              <p className="font-bold text-zinc-500 text-xs">Preview unavailable while status is not Completed.</p>
            </div>
          )}
        </div>
      )
    }
  ];

  return (
    <Modal
      title={
        <div className="flex items-center justify-between pb-2 text-slate-800 dark:text-white border-b border-zinc-100 dark:border-zinc-800">
          <div className="flex items-center gap-2">
            <FileText size={18} className="text-[var(--primary)]" />
            <span className="text-sm font-extrabold uppercase tracking-wide">Report Detailed View</span>
          </div>
          <span className="text-xs text-zinc-400 font-bold mr-6">{report.reportNumber}</span>
        </div>
      }
      open={visible}
      onCancel={onClose}
      width={1100}
      footer={[
        <Button 
          key="close" 
          onClick={onClose}
          className="border-zinc-250 dark:border-zinc-850 text-zinc-700 dark:text-zinc-300 font-bold rounded-xl h-10 px-5 cursor-pointer"
        >
          Close
        </Button>,
        report.status === "Failed" && (
          <Button
            key="retry"
            type="primary"
            onClick={handleRegenerate}
            loading={regenerating}
            className="bg-[var(--primary)] border-[var(--primary)] hover:bg-[var(--primary-hover)] text-white font-bold rounded-xl h-10 px-5 cursor-pointer flex items-center gap-1"
          >
            <RefreshCw size={13} className={regenerating ? "animate-spin" : ""} />
            <span>Retry Generation</span>
          </Button>
        ),
        report.status === "Completed" && (
          <Button
            key="regenerate"
            onClick={handleRegenerate}
            loading={regenerating}
            className="border-zinc-200 hover:border-[var(--primary)] hover:text-[var(--primary)] font-bold rounded-xl h-10 px-5 cursor-pointer flex items-center gap-1"
          >
            <RefreshCw size={13} className={regenerating ? "animate-spin" : ""} />
            <span>Regenerate</span>
          </Button>
        ),
        report.status === "Completed" && (
          <Button
            key="download"
            type="primary"
            onClick={() => onDownload(report._id)}
            className="bg-[var(--primary)] border-[var(--primary)] hover:bg-[var(--primary-hover)] text-white font-bold rounded-xl h-10 px-5 cursor-pointer flex items-center gap-1"
          >
            <Download size={13} />
            <span>Download</span>
          </Button>
        )
      ].filter(Boolean)}
      centered
      className="reports-modal dark:bg-zinc-900"
    >
      <Tabs activeKey={activeTab} onChange={setActiveTab} items={tabsItems} className="mt-2 font-semibold" />
    </Modal>
  );
}
