import React from "react";
import { X, FileText, FileSpreadsheet, Printer, Download, RefreshCw } from "lucide-react";
import { useExportStaffReport } from "../hooks/useStaffReport";
import { toast } from "sonner";

export default function ExportStaffReportModal({ isOpen, reportId, onClose }) {
  const { data: report, isLoading, error } = useExportStaffReport(reportId);

  if (!isOpen) return null;

  const handlePrint = () => {
    if (!report) return;
    toast.success("Opening print dialog...");
    const printWindow = window.open("", "_blank");
    printWindow.document.write(`
      <html>
        <head>
          <title>Staff Report - ${report.id}</title>
          <style>
            body { font-family: sans-serif; padding: 40px; color: #333; }
            .header { border-bottom: 2px solid #eee; padding-bottom: 20px; margin-bottom: 20px; }
            .detail-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 10px; margin-top: 20px; }
          </style>
        </head>
        <body>
          <div class="header">
            <h2>PAPA VEG PIZZA</h2>
            <h3>Staff Summary Analytics Report Log</h3>
            <p>Report ID: ${report.id}</p>
          </div>
          <div class="detail-grid">
            <p><strong>Target Role:</strong> ${report.role}</p>
            <p><strong>Target Store:</strong> ${report.storeName}</p>
            <p><strong>Start Date:</strong> ${report.startDate}</p>
            <p><strong>End Date:</strong> ${report.endDate}</p>
            <p><strong>Generated By:</strong> ${report.generatedBy}</p>
            <p><strong>Created At:</strong> ${new Date(report.createdAt).toLocaleString()}</p>
            <p><strong>Status:</strong> ${report.status}</p>
          </div>
          <script>window.print();</script>
        </body>
      </html>
    `);
    printWindow.document.close();
    onClose();
  };

  const handleDownload = (format) => {
    if (!report) return;
    toast.success(`Downloading staff report summary as ${format}...`);

    let content = `
Papa Veg Pizza Staff Report Summary Log
Report ID: ${report.id}
Target Role: ${report.role}
Store: ${report.storeName}
Date Period: ${report.startDate} to ${report.endDate}
Generated By: ${report.generatedBy}
Created At: ${report.createdAt}
Status: ${report.status}
`;

    const blob = new Blob([content], { type: "text/plain;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.download = `staff-report-${report.id}.${format.toLowerCase() === "excel" ? "csv" : "txt"}`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    onClose();
  };

  return (
    <div className="fixed inset-0 lg:left-[280px] z-50 overflow-hidden text-xs select-none">
      {/* Backdrop */}
      <div 
        className="absolute inset-0 bg-black/50 backdrop-blur-xs z-50" 
        onClick={onClose} 
      />

      {/* Modal Container */}
      <div className="absolute inset-0 z-50 flex items-center justify-center p-4">
        <div className="w-full max-w-sm bg-white dark:bg-zinc-950 border border-zinc-200 dark:border-zinc-800 rounded-2xl shadow-2xl flex flex-col overflow-hidden animate-scale-up font-semibold text-zinc-750 dark:text-zinc-350">
          
          {/* Header */}
          <header className="p-3.5 border-b border-zinc-150 dark:border-zinc-850 flex items-center justify-between bg-zinc-50/50 dark:bg-zinc-900/30">
            <h3 className="text-sm font-black tracking-tight text-slate-900 dark:text-white">
              Export Staff Report
            </h3>
            <button onClick={onClose} className="p-1.5 rounded-lg hover:bg-zinc-100 dark:hover:bg-zinc-900 text-zinc-400 cursor-pointer">
              <X size={14} />
            </button>
          </header>

          {isLoading ? (
            <div className="p-8 flex flex-col items-center justify-center space-y-3">
              <RefreshCw className="animate-spin text-[var(--primary)]" size={24} />
              <p className="text-[10px] text-zinc-400 font-bold">Loading report data...</p>
            </div>
          ) : error || !report ? (
            <div className="p-6 text-center text-red-500 font-bold">
              Failed to load staff report data.
            </div>
          ) : (
            <div className="p-4 space-y-4">
              <div className="bg-zinc-50 dark:bg-zinc-900 p-3 rounded-xl border border-zinc-150 dark:border-zinc-850 space-y-1">
                <span className="text-[10px] text-zinc-400 block">Target Report</span>
                <span className="text-zinc-800 dark:text-zinc-200 font-bold block">{report.id}</span>
                <span className="text-[9px] text-zinc-400 block">Role: {report.role} • Store: {report.storeName}</span>
              </div>

              <div className="space-y-2">
                <button
                  onClick={() => handleDownload("PDF")}
                  className="w-full p-3 border border-zinc-200 dark:border-zinc-850 hover:border-[var(--primary)]/30 bg-zinc-50/10 hover:bg-zinc-50 dark:hover:bg-zinc-900/30 rounded-xl transition-all duration-200 flex items-center justify-between text-zinc-800 dark:text-zinc-200 cursor-pointer"
                >
                  <div className="flex items-center gap-2">
                    <span className="p-1.5 bg-red-500/10 text-red-500 rounded-lg">
                      <FileText size={14} />
                    </span>
                    <span className="font-bold">Export PDF Document</span>
                  </div>
                  <Download size={14} className="text-zinc-400" />
                </button>

                <button
                  onClick={() => handleDownload("Excel")}
                  className="w-full p-3 border border-zinc-200 dark:border-zinc-855 hover:border-[var(--primary)]/30 bg-zinc-50/10 hover:bg-zinc-50 dark:hover:bg-zinc-900/30 rounded-xl transition-all duration-200 flex items-center justify-between text-zinc-800 dark:text-zinc-200 cursor-pointer"
                >
                  <div className="flex items-center gap-2">
                    <span className="p-1.5 bg-emerald-500/10 text-emerald-500 rounded-lg">
                      <FileSpreadsheet size={14} />
                    </span>
                    <span className="font-bold">Export Excel Spreadsheet</span>
                  </div>
                  <Download size={14} className="text-zinc-400" />
                </button>

                <button
                  onClick={handlePrint}
                  className="w-full p-3 border border-zinc-200 dark:border-zinc-850 hover:border-[var(--primary)]/30 bg-zinc-50/10 hover:bg-zinc-50 dark:hover:bg-zinc-900/30 rounded-xl transition-all duration-200 flex items-center justify-between text-zinc-800 dark:text-zinc-200 cursor-pointer"
                >
                  <div className="flex items-center gap-2">
                    <span className="p-1.5 bg-blue-500/10 text-blue-500 rounded-lg">
                      <Printer size={14} />
                    </span>
                    <span className="font-bold">Print Summary Log</span>
                  </div>
                  <Printer size={14} className="text-zinc-400" />
                </button>
              </div>

              <div className="flex justify-end pt-2 border-t border-zinc-100 dark:border-zinc-900">
                <button
                  onClick={onClose}
                  className="px-4 py-2 border border-zinc-200 dark:border-zinc-800 hover:bg-zinc-50 dark:hover:bg-zinc-900 rounded-lg font-bold cursor-pointer text-zinc-800 dark:text-zinc-200"
                >
                  Cancel
                </button>
              </div>
            </div>
          )}

        </div>
      </div>
    </div>
  );
}
