import React, { useState } from "react";
import { X, DollarSign, ShoppingBag, RotateCcw, Percent, BarChart3, TrendingUp, CreditCard, Pizza, Download, Printer } from "lucide-react";
import {
  ResponsiveContainer,
  LineChart,
  Line,
  BarChart,
  Bar,
  PieChart,
  Pie,
  XAxis,
  YAxis,
  Tooltip as RechartsTooltip,
  Legend,
  Cell
} from "recharts";
import { useSingleReport } from "../hooks/useSalesReport";
import { toast } from "sonner";

export default function ViewReportModal({ isOpen, reportId, onClose }) {
  const { data, isLoading, error } = useSingleReport(reportId);
  const [activeTab, setActiveTab] = useState("summary");

  if (!isOpen) return null;

  const summary = data?.summary;
  const trend = data?.trend;
  const paymentSplit = data?.paymentSplit;
  const storePerformance = data?.storePerformance;
  const topProducts = data?.topProducts;
  const reportDetails = data?.report;

  // Custom colors for charts
  const COLORS = {
    upi: "var(--primary)",
    card: "#3b82f6",
    cash: "#10b981",
    wallet: "#f59e0b"
  };

  const pieData = paymentSplit ? [
    { name: "UPI", value: paymentSplit.upi, color: COLORS.upi },
    { name: "Card", value: paymentSplit.card, color: COLORS.card },
    { name: "Cash", value: paymentSplit.cash, color: COLORS.cash },
    { name: "Wallet", value: paymentSplit.wallet, color: COLORS.wallet }
  ] : [];

  const handlePrint = () => {
    window.print();
  };

  const handleDownload = (format) => {
    toast.success(`Exporting report as ${format}...`);
    
    // Create a simple text block representing the report data to download
    const reportTxt = `
Papa Veg Pizza Sales Report - ${reportDetails?.id || "N/A"}
--------------------------------------------------
Report Type: ${reportDetails?.reportType}
Date Range: ${reportDetails?.startDate} to ${reportDetails?.endDate}
Generated By: ${reportDetails?.generatedBy}
Created At: ${reportDetails?.createdAt}

SUMMARY METRICS:
- Total Revenue: INR ${summary?.revenue?.toLocaleString("en-IN")}
- Total Orders: ${summary?.orders}
- Refund Amount: INR ${summary?.refunds?.toLocaleString("en-IN")}
- Taxes Collected: INR ${summary?.taxes?.toLocaleString("en-IN")}
- Net Revenue: INR ${summary?.netRevenue?.toLocaleString("en-IN")}
- Growth: ${summary?.growthPercentage}%
`;

    const blob = new Blob([reportTxt], { type: "text/plain;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.download = `${reportDetails?.id || "Sales-Report"}.${format.toLowerCase()}`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  return (
    <div className="fixed inset-0 lg:left-[280px] z-50 overflow-hidden flex flex-col bg-zinc-50 dark:bg-zinc-950 text-xs">
      
      {/* Fullscreen Header */}
      <header className="px-6 py-4 border-b border-zinc-200 dark:border-zinc-800 bg-white dark:bg-zinc-900 flex justify-between items-center shadow-sm shrink-0">
        <div>
          <div className="flex items-center gap-2">
            <span className="p-1 rounded-md bg-[var(--primary)]/10 text-[var(--primary)] font-bold text-[10px]">
              {reportDetails?.reportType || "Sales Report"}
            </span>
            <h2 className="text-sm md:text-base font-black text-slate-900 dark:text-white">
              Report Details: {reportDetails?.id || "Loading..."}
            </h2>
          </div>
          {reportDetails && (
            <p className="text-[10px] text-zinc-400 font-bold mt-0.5">
              Period: {reportDetails.startDate} to {reportDetails.endDate} • Generated by {reportDetails.generatedBy}
            </p>
          )}
        </div>
        <button 
          onClick={onClose} 
          className="p-2 rounded-xl bg-zinc-100 hover:bg-zinc-200 dark:bg-zinc-800 dark:hover:bg-zinc-700 text-zinc-500 dark:text-zinc-300 transition-colors cursor-pointer"
        >
          <X size={16} />
        </button>
      </header>

      {/* Tabs list */}
      <div className="px-6 border-b border-zinc-250 dark:border-zinc-850 bg-white dark:bg-zinc-900/50 flex gap-2 shrink-0">
        {[
          { id: "summary", label: "Summary Overview", icon: DollarSign },
          { id: "trend", label: "Revenue Trend", icon: TrendingUp },
          { id: "payments", label: "Payment Split", icon: CreditCard },
          { id: "stores", label: "Store Performance", icon: BarChart3 },
          { id: "products", label: "Top Selling Products", icon: Pizza }
        ].map((tab) => {
          const Icon = tab.icon;
          return (
            <button
              key={tab.id}
              onClick={() => setActiveTab(tab.id)}
              className={`py-3.5 px-4 font-bold border-b-2 transition-all flex items-center gap-1.5 cursor-pointer ${
                activeTab === tab.id
                  ? "border-[var(--primary)] text-[var(--primary)] font-black"
                  : "border-transparent text-zinc-500 dark:text-zinc-400 hover:text-zinc-850 dark:hover:text-zinc-200"
              }`}
            >
              <Icon size={13} />
              <span>{tab.label}</span>
            </button>
          );
        })}
      </div>

      {/* Scrollable Details Area */}
      <main className="flex-1 overflow-y-auto p-6 scrollbar-thin">
        {isLoading ? (
          /* Loading Skeleton View */
          <div className="space-y-6">
            <div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-6 gap-3">
              {[...Array(6)].map((_, i) => (
                <div key={i} className="bg-white dark:bg-zinc-900 p-4 border border-zinc-200 dark:border-zinc-850 rounded-xl animate-pulse space-y-2">
                  <div className="h-3 w-16 bg-zinc-150 dark:bg-zinc-800 rounded" />
                  <div className="h-6 w-24 bg-zinc-200 dark:bg-zinc-750 rounded" />
                </div>
              ))}
            </div>
            <div className="h-[300px] w-full bg-white dark:bg-zinc-900 border border-zinc-200 dark:border-zinc-850 rounded-xl animate-pulse flex items-center justify-center">
              <div className="h-8 w-8 rounded-full border-4 border-dashed border-[var(--primary)] animate-spin" />
            </div>
          </div>
        ) : error ? (
          /* Error Screen */
          <div className="text-center py-16 bg-white dark:bg-zinc-900 rounded-2xl border border-dashed border-red-250 dark:border-red-900/30 p-8 max-w-md mx-auto my-12">
            <AlertTriangle className="mx-auto text-red-500 stroke-[1.5] mb-3" size={32} />
            <h3 className="text-sm font-bold text-slate-900 dark:text-white">Failed to Load Report</h3>
            <p className="text-[10px] text-zinc-400 mt-1">There was an issue fetching the database details for report ID {reportId}.</p>
          </div>
        ) : (
          /* Content Tabs */
          <div className="animate-fade-in space-y-6">
            
            {/* Tab: SUMMARY */}
            {activeTab === "summary" && (
              <div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-6 gap-3">
                
                {/* Total Revenue */}
                <div className="bg-white dark:bg-zinc-900 border border-zinc-150 dark:border-zinc-850 p-4 rounded-xl shadow-sm flex items-center justify-between">
                  <div>
                    <p className="text-[10px] font-bold text-zinc-400 uppercase tracking-wider">Total Revenue</p>
                    <p className="text-base font-black text-slate-900 dark:text-white mt-1">₹{summary.revenue.toLocaleString("en-IN")}</p>
                    <p className="text-[9px] text-zinc-400 font-semibold mt-1">Successful payments index</p>
                  </div>
                  <span className="p-2 bg-emerald-50 dark:bg-emerald-950/20 text-emerald-600 dark:text-emerald-400 border border-emerald-500/10 rounded-lg">
                    <DollarSign size={15} />
                  </span>
                </div>

                {/* Total Orders */}
                <div className="bg-white dark:bg-zinc-900 border border-zinc-150 dark:border-zinc-850 p-4 rounded-xl shadow-sm flex items-center justify-between">
                  <div>
                    <p className="text-[10px] font-bold text-zinc-400 uppercase tracking-wider">Total Orders</p>
                    <p className="text-base font-black text-slate-900 dark:text-white mt-1">{summary.orders}</p>
                    <p className="text-[9px] text-zinc-400 font-semibold mt-1">Orders processed count</p>
                  </div>
                  <span className="p-2 bg-rose-50 dark:bg-rose-950/20 text-rose-600 dark:text-rose-400 border border-rose-500/10 rounded-lg">
                    <ShoppingBag size={15} />
                  </span>
                </div>

                {/* Average Order Value */}
                <div className="bg-white dark:bg-zinc-900 border border-zinc-150 dark:border-zinc-850 p-4 rounded-xl shadow-sm flex items-center justify-between">
                  <div>
                    <p className="text-[10px] font-bold text-zinc-400 uppercase tracking-wider">Avg Order Value</p>
                    <p className="text-base font-black text-slate-900 dark:text-white mt-1">₹{Math.floor(summary.revenue / summary.orders).toLocaleString("en-IN")}</p>
                    <p className="text-[9px] text-zinc-400 font-semibold mt-1">Revenue / Orders ratio</p>
                  </div>
                  <span className="p-2 bg-amber-50 dark:bg-amber-950/20 text-amber-600 dark:text-amber-400 border border-amber-500/10 rounded-lg">
                    <Percent size={15} />
                  </span>
                </div>

                {/* Refund Amount */}
                <div className="bg-white dark:bg-zinc-900 border border-zinc-150 dark:border-zinc-850 p-4 rounded-xl shadow-sm flex items-center justify-between">
                  <div>
                    <p className="text-[10px] font-bold text-zinc-400 uppercase tracking-wider">Refund Amount</p>
                    <p className="text-base font-black text-slate-900 dark:text-white mt-1">₹{summary.refunds.toLocaleString("en-IN")}</p>
                    <p className="text-[9px] text-zinc-400 font-semibold mt-1">Total customer refunds</p>
                  </div>
                  <span className="p-2 bg-zinc-50 dark:bg-zinc-800 text-zinc-600 dark:text-zinc-300 border border-zinc-200 dark:border-zinc-700 rounded-lg">
                    <RotateCcw size={15} />
                  </span>
                </div>

                {/* Taxes Collected */}
                <div className="bg-white dark:bg-zinc-900 border border-zinc-150 dark:border-zinc-850 p-4 rounded-xl shadow-sm flex items-center justify-between">
                  <div>
                    <p className="text-[10px] font-bold text-zinc-400 uppercase tracking-wider">Taxes Collected</p>
                    <p className="text-base font-black text-slate-900 dark:text-white mt-1">₹{summary.taxes.toLocaleString("en-IN")}</p>
                    <p className="text-[9px] text-zinc-400 font-semibold mt-1">GST collected index (5%)</p>
                  </div>
                  <span className="p-2 bg-blue-50 dark:bg-blue-950/20 text-blue-600 dark:text-blue-400 border border-blue-500/10 rounded-lg">
                    <Percent size={15} />
                  </span>
                </div>

                {/* Net Revenue */}
                <div className="bg-white dark:bg-zinc-900 border border-zinc-150 dark:border-zinc-850 p-4 rounded-xl shadow-sm flex items-center justify-between">
                  <div>
                    <p className="text-[10px] font-bold text-zinc-400 uppercase tracking-wider">Net Revenue</p>
                    <p className="text-base font-black text-slate-900 dark:text-white mt-1">₹{summary.netRevenue.toLocaleString("en-IN")}</p>
                    <p className="text-[9px] text-zinc-400 font-semibold mt-1">Revenue - Refunds - Taxes</p>
                  </div>
                  <span className="p-2 bg-indigo-50 dark:bg-indigo-950/20 text-indigo-600 dark:text-indigo-400 border border-indigo-500/10 rounded-lg">
                    <DollarSign size={15} />
                  </span>
                </div>

              </div>
            )}

            {/* Tab: REVENUE TREND (Line Chart) */}
            {activeTab === "trend" && (
              <div className="bg-white dark:bg-zinc-900 border border-zinc-200 dark:border-zinc-800 p-6 rounded-xl shadow-sm">
                <h3 className="font-extrabold text-xs text-slate-900 dark:text-white mb-4">Revenue Trend Chart</h3>
                <div className="w-full h-[350px] overflow-x-auto scrollbar-thin">
                  <div className="w-[600px] h-[330px]">
                    <LineChart width={600} height={330} data={trend} margin={{ top: 10, right: 10, left: -20, bottom: 0 }}>
                      <XAxis dataKey="date" stroke="#888888" fontSize={10} tickLine={false} axisLine={false} />
                      <YAxis stroke="#888888" fontSize={10} tickLine={false} axisLine={false} tickFormatter={(val) => `₹${val >= 1000 ? `${(val / 1000).toFixed(0)}k` : val}`} />
                      <RechartsTooltip contentStyle={{ fontSize: "10px", borderRadius: "8px" }} />
                      <Legend verticalAlign="top" height={36} iconType="circle" />
                      <Line type="monotone" dataKey="revenue" name="Revenue Trends" stroke="var(--primary)" strokeWidth={2.5} activeDot={{ r: 6 }} />
                    </LineChart>
                  </div>
                </div>
              </div>
            )}

            {/* Tab: PAYMENT SPLIT (Pie Chart) */}
            {activeTab === "payments" && (
              <div className="bg-white dark:bg-zinc-900 border border-zinc-200 dark:border-zinc-800 p-6 rounded-xl shadow-sm flex flex-col md:flex-row gap-8 items-center">
                <div className="w-full max-w-sm h-[260px] flex items-center justify-center">
                  <div className="w-[240px] h-[240px]">
                    <PieChart width={240} height={240}>
                      <Pie
                        data={pieData}
                        cx="50%"
                        cy="50%"
                        innerRadius={60}
                        outerRadius={90}
                        paddingAngle={3}
                        dataKey="value"
                      >
                        {pieData.map((entry, index) => (
                          <Cell key={`cell-${index}`} fill={entry.color} />
                        ))}
                      </Pie>
                      <RechartsTooltip formatter={(val) => `${val}%`} contentStyle={{ fontSize: "10px", borderRadius: "8px" }} />
                      <Legend />
                    </PieChart>
                  </div>
                </div>
                <div className="flex-1 space-y-4">
                  <h3 className="font-extrabold text-xs text-slate-900 dark:text-white">Payment Method Distribution</h3>
                  <p className="text-[10px] text-zinc-400 leading-normal">
                    This chart breaks down the total sales across the franchise by payment methods. UPI payments constitute the majority share, highlighting the rapid adoption of digital settlements.
                  </p>
                  <div className="grid grid-cols-2 gap-3.5">
                    {pieData.map((d) => (
                      <div key={d.name} className="p-3 border border-zinc-100 dark:border-zinc-800 rounded-lg flex items-center justify-between">
                        <span className="flex items-center gap-1.5 font-bold">
                          <span className="w-2.5 h-2.5 rounded-full" style={{ backgroundColor: d.color }} />
                          {d.name}
                        </span>
                        <span className="font-black text-slate-900 dark:text-white">{d.value}%</span>
                      </div>
                    ))}
                  </div>
                </div>
              </div>
            )}

            {/* Tab: STORE PERFORMANCE (Bar Chart) */}
            {activeTab === "stores" && (
              <div className="bg-white dark:bg-zinc-900 border border-zinc-200 dark:border-zinc-800 p-6 rounded-xl shadow-sm space-y-6">
                <h3 className="font-extrabold text-xs text-slate-900 dark:text-white">Store Revenue Comparison</h3>
                <div className="w-full h-[280px] overflow-x-auto scrollbar-thin">
                  <div className="w-[500px] h-[270px]">
                    <BarChart width={500} height={270} data={storePerformance} margin={{ top: 10, right: 10, left: -20, bottom: 0 }}>
                      <XAxis dataKey="storeName" stroke="#888888" fontSize={9} tickLine={false} axisLine={false} tickFormatter={(name) => name.replace("Papa Veg Pizza - ", "")} />
                      <YAxis stroke="#888888" fontSize={9} tickLine={false} axisLine={false} tickFormatter={(val) => `₹${val >= 100000 ? `${(val / 100000).toFixed(1)}L` : val}`} />
                      <RechartsTooltip contentStyle={{ fontSize: "10px", borderRadius: "8px" }} />
                      <Bar dataKey="revenue" name="Store Sales" fill="var(--sa-secondary)" radius={[4, 4, 0, 0]}>
                        {storePerformance.map((entry, idx) => (
                          <Cell key={`cell-${idx}`} fill={idx === 0 ? "var(--primary)" : "var(--sa-secondary)"} />
                        ))}
                      </Bar>
                    </BarChart>
                  </div>
                </div>

                {/* Table representation */}
                <div className="overflow-x-auto">
                  <table className="w-full text-[10px] text-left border-collapse border border-zinc-150 dark:border-zinc-850">
                    <thead>
                      <tr className="bg-zinc-50 dark:bg-zinc-900 border-b border-zinc-200 dark:border-zinc-800 text-zinc-500 font-bold uppercase tracking-wider">
                        <th className="p-3">Store Name</th>
                        <th className="p-3 text-right">Orders</th>
                        <th className="p-3 text-right">Revenue</th>
                        <th className="p-3 text-right">AOV</th>
                        <th className="p-3 text-right">Growth %</th>
                      </tr>
                    </thead>
                    <tbody className="divide-y divide-zinc-150 dark:divide-zinc-800 font-medium">
                      {storePerformance.map((sp) => (
                        <tr key={sp.storeId} className="hover:bg-zinc-50/50 dark:hover:bg-zinc-900/10 text-slate-800 dark:text-zinc-300">
                          <td className="p-3 font-bold">{sp.storeName}</td>
                          <td className="p-3 text-right">{sp.orders.toLocaleString()}</td>
                          <td className="p-3 text-right font-black">₹{sp.revenue.toLocaleString("en-IN")}</td>
                          <td className="p-3 text-right">₹{Math.floor(sp.avgOrderValue).toLocaleString()}</td>
                          <td className={`p-3 text-right font-bold ${sp.growthPercentage >= 0 ? "text-emerald-600" : "text-rose-600"}`}>
                            {sp.growthPercentage >= 0 ? `+${sp.growthPercentage}` : sp.growthPercentage}%
                          </td>
                        </tr>
                      ))}
                    </tbody>
                  </table>
                </div>
              </div>
            )}

            {/* Tab: TOP PRODUCTS */}
            {activeTab === "products" && (
              <div className="bg-white dark:bg-zinc-900 border border-zinc-200 dark:border-zinc-800 p-6 rounded-xl shadow-sm space-y-4">
                <h3 className="font-extrabold text-xs text-slate-900 dark:text-white">Top Selling Products Breakdown</h3>
                <div className="overflow-x-auto">
                  <table className="w-full text-[10px] text-left border-collapse border border-zinc-150 dark:border-zinc-850">
                    <thead>
                      <tr className="bg-zinc-50 dark:bg-zinc-900 border-b border-zinc-200 dark:border-zinc-800 text-zinc-500 font-bold uppercase tracking-wider">
                        <th className="p-3">Product</th>
                        <th className="p-3 text-right">Quantity Sold</th>
                        <th className="p-3 text-right">Revenue</th>
                        <th className="p-3 text-right">Contribution %</th>
                      </tr>
                    </thead>
                    <tbody className="divide-y divide-zinc-150 dark:divide-zinc-800 font-semibold text-slate-800 dark:text-zinc-300">
                      {topProducts.map((p) => (
                        <tr key={p.productId} className="hover:bg-zinc-50/50 dark:hover:bg-zinc-900/10">
                          <td className="p-3 flex items-center gap-2.5">
                            <img src={p.image} alt={p.productName} className="w-7 h-7 rounded-lg object-cover border border-zinc-150 dark:border-zinc-800" />
                            <span className="font-bold">{p.productName}</span>
                          </td>
                          <td className="p-3 text-right">{p.quantitySold.toLocaleString()}</td>
                          <td className="p-3 text-right font-black">₹{p.revenue.toLocaleString("en-IN")}</td>
                          <td className="p-3 text-right">
                            <div className="flex items-center justify-end gap-2">
                              <span>{p.contributionPercentage}%</span>
                              <div className="w-16 bg-zinc-100 dark:bg-zinc-800 h-1.5 rounded-full overflow-hidden">
                                <div className="bg-[var(--primary)] h-full rounded-full" style={{ width: `${p.contributionPercentage}%` }} />
                              </div>
                            </div>
                          </td>
                        </tr>
                      ))}
                    </tbody>
                  </table>
                </div>
              </div>
            )}

          </div>
        )}
      </main>

      {/* Footer Controls */}
      <footer className="px-6 py-4 border-t border-zinc-250 dark:border-zinc-800 bg-white dark:bg-zinc-900 flex justify-between items-center shadow-inner shrink-0">
        <div className="flex items-center gap-2">
          <button
            onClick={() => handleDownload("PDF")}
            disabled={isLoading || !data}
            className="px-3 py-2 bg-[var(--primary)] hover:bg-[var(--primary-hover)] text-white font-bold rounded-lg shadow flex items-center gap-1.5 cursor-pointer disabled:opacity-50"
          >
            <Download size={13} />
            <span>Download PDF</span>
          </button>
          <button
            onClick={() => handleDownload("Excel")}
            disabled={isLoading || !data}
            className="px-3 py-2 border border-zinc-250 dark:border-zinc-850 bg-white dark:bg-zinc-900 hover:bg-zinc-50 dark:hover:bg-zinc-800 font-bold rounded-lg shadow-sm flex items-center gap-1.5 cursor-pointer disabled:opacity-50 text-slate-800 dark:text-zinc-250"
          >
            <Download size={13} />
            <span>Download Excel</span>
          </button>
          <button
            onClick={handlePrint}
            disabled={isLoading || !data}
            className="px-3 py-2 border border-zinc-250 dark:border-zinc-850 bg-white dark:bg-zinc-900 hover:bg-zinc-50 dark:hover:bg-zinc-800 font-bold rounded-lg shadow-sm flex items-center gap-1.5 cursor-pointer disabled:opacity-50 text-slate-800 dark:text-zinc-250"
          >
            <Printer size={13} />
            <span>Print Report</span>
          </button>
        </div>

        <button
          onClick={onClose}
          className="px-4 py-2 border border-zinc-250 dark:border-zinc-800 bg-white dark:bg-zinc-900 hover:bg-zinc-50 dark:hover:bg-zinc-850 font-bold rounded-lg text-slate-800 dark:text-zinc-200 cursor-pointer"
        >
          Close
        </button>
      </footer>

    </div>
  );
}
