import { useState, useEffect, useCallback, useMemo } from "react";
import { toast } from "sonner";
import { mockGeneratedReports, mockScheduledReports, mockStores } from "../mockData";

export function useReports() {
  const [loading, setLoading] = useState(false);
  const [rawReports, setRawReports] = useState([]);
  const [rawSchedules, setRawSchedules] = useState([]);

  // Filter States
  const [search, setSearch] = useState("");
  const [debouncedSearch, setDebouncedSearch] = useState("");
  const [reportType, setReportType] = useState("All");
  const [status, setStatus] = useState("All");
  const [generatedBy, setGeneratedBy] = useState("All");
  const [dateFilter, setDateFilter] = useState("This Month");
  const [customRange, setCustomRange] = useState({ start: null, end: null });

  // Pagination & Sorting States
  const [currentPage, setCurrentPage] = useState(1);
  const [pageSize, setPageSize] = useState(20);
  const [sortBy, setSortBy] = useState("createdAt");
  const [sortOrder, setSortOrder] = useState("desc");

  // Selection for bulk actions
  const [selectedRowKeys, setSelectedRowKeys] = useState([]);

  // Modal / Drawer state
  const [selectedReport, setSelectedReport] = useState(null);
  const [selectedSchedule, setSelectedSchedule] = useState(null);

  // Initialize from Mock DB
  useEffect(() => {
    setLoading(true);
    const timer = setTimeout(() => {
      setRawReports(mockGeneratedReports);
      setRawSchedules(mockScheduledReports);
      setLoading(false);
    }, 500);
    return () => clearTimeout(timer);
  }, []);

  // Search Debouncing
  useEffect(() => {
    const handler = setTimeout(() => {
      setDebouncedSearch(search);
    }, 300);
    return () => clearTimeout(handler);
  }, [search]);

  // Simulated BullMQ Queue Progress & State update polling every 15 seconds
  useEffect(() => {
    const interval = setInterval(() => {
      let updatedAny = false;
      setRawReports(prev => {
        const nextList = prev.map(rep => {
          if (rep.status === "Generating") {
            updatedAny = true;
            // 90% chance to complete, 10% chance to fail
            const success = Math.random() > 0.1;
            return {
              ...rep,
              status: success ? "Completed" : "Failed",
              fileUrl: success ? "https://pdfobject.com/pdf/sample.pdf" : "",
              fileSize: success ? `${(1.0 + Math.random() * 3).toFixed(1)} MB` : "--",
              duration: `${(1.0 + Math.random() * 4).toFixed(1)}s`
            };
          }
          return rep;
        });

        if (updatedAny) {
          toast.success("BullMQ Queue updated: background report jobs completed!");
        }
        return nextList;
      });
    }, 15000);

    return () => clearInterval(interval);
  }, []);

  // Filter Logic
  const filteredReports = useMemo(() => {
    let result = [...rawReports];

    // Filter by Search Query (Number, Type)
    if (debouncedSearch.trim()) {
      const query = debouncedSearch.toLowerCase();
      result = result.filter(r =>
        r.reportNumber.toLowerCase().includes(query) ||
        r.reportType.toLowerCase().includes(query)
      );
    }

    // Filter by Report Type
    if (reportType !== "All") {
      result = result.filter(r => r.reportType === reportType);
    }

    // Filter by Status
    if (status !== "All") {
      result = result.filter(r => r.status === status);
    }

    // Filter by Generated By
    if (generatedBy !== "All") {
      result = result.filter(r => r.generatedBy === generatedBy);
    }

    // Filter by Date Range
    const todayStr = new Date().toISOString().split("T")[0];
    const now = new Date();

    if (dateFilter === "Today") {
      result = result.filter(r => r.createdAt.split("T")[0] === todayStr);
    } else if (dateFilter === "Last 7 Days") {
      const threshold = new Date();
      threshold.setDate(now.getDate() - 7);
      result = result.filter(r => new Date(r.createdAt) >= threshold);
    } else if (dateFilter === "This Month") {
      const month = now.getMonth();
      const year = now.getFullYear();
      result = result.filter(r => {
        const d = new Date(r.createdAt);
        return d.getMonth() === month && d.getFullYear() === year;
      });
    } else if (dateFilter === "Custom" && customRange.start && customRange.end) {
      const start = new Date(customRange.start);
      const end = new Date(customRange.end);
      start.setHours(0, 0, 0, 0);
      end.setHours(23, 59, 59, 999);
      result = result.filter(r => {
        const d = new Date(r.createdAt);
        return d >= start && d <= end;
      });
    }

    return result;
  }, [rawReports, debouncedSearch, reportType, status, generatedBy, dateFilter, customRange]);

  // Aggregate Statistics (Blue, Purple, Red, Green cards)
  const statistics = useMemo(() => {
    let generatedCount = 0;
    let scheduledCount = rawSchedules.length;
    let failedCount = 0;
    let downloadCountSum = 0;

    rawReports.forEach(r => {
      if (r.status === "Completed") {
        generatedCount++;
        downloadCountSum += (r.downloadCount || 0);
      } else if (r.status === "Failed") {
        failedCount++;
      }
    });

    return {
      generatedCount,
      scheduledCount,
      failedCount,
      downloadCountSum
    };
  }, [rawReports, rawSchedules]);

  // Pie Chart Data: Reports by Type
  const reportsByTypeChartData = useMemo(() => {
    const counts = {
      "Sales Report": 0,
      "Store Performance Report": 0,
      "Product Sales Report": 0,
      "Inventory Report": 0,
      "Rider Performance Report": 0,
      "Customer Report": 0,
      "Finance Report": 0
    };

    filteredReports.forEach(r => {
      if (counts[r.reportType] !== undefined) {
        counts[r.reportType]++;
      }
    });

    const colors = {
      "Sales Report": "#3b82f6", // Blue
      "Store Performance Report": "#10b981", // Green
      "Product Sales Report": "#f59e0b", // Amber
      "Inventory Report": "#ec4899", // Pink
      "Rider Performance Report": "#8b5cf6", // Purple
      "Customer Report": "#06b6d4", // Cyan
      "Finance Report": "#e11d48" // Rose
    };

    return Object.keys(counts).map(key => ({
      name: key.replace(" Report", ""),
      value: counts[key],
      color: colors[key] || "#6b7280"
    })).filter(item => item.value > 0);
  }, [filteredReports]);

  // Line Chart Data: Daily Report Trend
  const reportTrendChartData = useMemo(() => {
    const trendMap = {};
    filteredReports.forEach(r => {
      const dateStr = r.createdAt.split("T")[0];
      if (!trendMap[dateStr]) {
        trendMap[dateStr] = { date: dateStr, count: 0 };
      }
      trendMap[dateStr].count++;
    });

    return Object.values(trendMap)
      .sort((a, b) => new Date(a.date) - new Date(b.date))
      .map(item => ({
        ...item,
        formattedDate: new Date(item.date).toLocaleDateString("en-IN", { day: "2-digit", month: "short" })
      }));
  }, [filteredReports]);

  // Users List for Filters Dropdown
  const usersList = useMemo(() => {
    const usersSet = new Set(rawReports.map(r => r.generatedBy));
    return Array.from(usersSet);
  }, [rawReports]);

  // Paginated and Sorted Table Data
  const paginatedReportsTableData = useMemo(() => {
    const sorted = [...filteredReports].sort((a, b) => {
      let aVal = a[sortBy];
      let bVal = b[sortBy];

      if (sortBy === "createdAt" || sortBy === "startDate" || sortBy === "endDate") {
        return sortOrder === "asc"
          ? new Date(aVal) - new Date(bVal)
          : new Date(bVal) - new Date(aVal);
      }

      if (typeof aVal === "string") {
        return sortOrder === "asc"
          ? aVal.localeCompare(bVal)
          : bVal.localeCompare(aVal);
      }

      return sortOrder === "asc" ? aVal - bVal : bVal - aVal;
    });

    const startIndex = (currentPage - 1) * pageSize;
    return sorted.slice(startIndex, startIndex + pageSize);
  }, [filteredReports, sortBy, sortOrder, currentPage, pageSize]);

  // Actions: Generate Report (BullMQ simulated background task)
  const generateReport = useCallback((config) => {
    return new Promise((resolve) => {
      setLoading(true);
      setTimeout(() => {
        const randomNum = Math.floor(Math.random() * 9000) + 1000;
        const newReport = {
          _id: `rep-${Date.now()}`,
          reportNumber: `REP-2026-${randomNum}`,
          reportType: config.reportType,
          startDate: config.startDate,
          endDate: config.endDate,
          generatedBy: "Shubham Jamliya", // Current Admin Name
          fileUrl: "",
          status: "Generating",
          createdAt: new Date().toISOString(),
          fileSize: "--",
          duration: "--",
          jobId: `bull-job-${randomNum}`,
          stores: config.storeFilter || "All Stores",
          format: config.format || "PDF",
          includeCharts: !!config.includeCharts,
          includeSummary: !!config.includeSummary,
          downloadCount: 0
        };

        setRawReports(prev => [newReport, ...prev]);
        setLoading(false);
        toast.success("Report generation started successfully.");

        // Simulate BullMQ background processing: completes in 4 seconds
        setTimeout(() => {
          setRawReports(prev =>
            prev.map(r => {
              if (r._id === newReport._id) {
                const success = Math.random() > 0.05; // 95% success rate
                if (success) {
                  toast.success(`Report ${r.reportNumber} compiled successfully!`);
                } else {
                  toast.error(`Report ${r.reportNumber} generation failed.`);
                }
                return {
                  ...r,
                  status: success ? "Completed" : "Failed",
                  fileUrl: success ? "https://pdfobject.com/pdf/sample.pdf" : "",
                  fileSize: success ? `${(1.2 + Math.random() * 3).toFixed(1)} MB` : "--",
                  duration: `${(1.2 + Math.random() * 3).toFixed(1)}s`
                };
              }
              return r;
            })
          );
        }, 4000);

        resolve(newReport);
      }, 500);
    });
  }, []);

  // Actions: Download Report
  const downloadReport = useCallback((id) => {
    return new Promise((resolve) => {
      setRawReports(prev =>
        prev.map(r => {
          if (r._id === id) {
            const nextCount = (r.downloadCount || 0) + 1;
            // Trigger actual browser download mock
            const link = document.createElement("a");
            link.href = r.fileUrl || "https://pdfobject.com/pdf/sample.pdf";
            link.target = "_blank";
            link.download = `${r.reportType.replace(/ /g, "_")}_${r.reportNumber}.${r.format.toLowerCase()}`;
            document.body.appendChild(link);
            link.click();
            document.body.removeChild(link);

            toast.success(`Downloading ${r.reportNumber} as ${r.format}...`);
            return { ...r, downloadCount: nextCount };
          }
          return r;
        })
      );
      resolve(true);
    });
  }, []);

  // Actions: Retry Generation
  const retryReport = useCallback((id) => {
    return new Promise((resolve) => {
      setRawReports(prev =>
        prev.map(r => {
          if (r._id === id) {
            toast.info(`Retrying report generation for ${r.reportNumber}...`);
            // Set back to generating
            setTimeout(() => {
              setRawReports(next =>
                next.map(item => {
                  if (item._id === id) {
                    toast.success(`Report ${item.reportNumber} generated on retry!`);
                    return {
                      ...item,
                      status: "Completed",
                      fileUrl: "https://pdfobject.com/pdf/sample.pdf",
                      fileSize: "2.1 MB",
                      duration: "1.9s"
                    };
                  }
                  return item;
                })
              );
            }, 3000);
            return { ...r, status: "Generating" };
          }
          return r;
        })
      );
      resolve(true);
    });
  }, []);

  // Actions: Delete Report
  const deleteReport = useCallback((id) => {
    return new Promise((resolve) => {
      setRawReports(prev => prev.filter(r => r._id !== id));
      setSelectedRowKeys(prev => prev.filter(key => key !== id));
      toast.success("Report deleted successfully.");
      resolve(true);
    });
  }, []);

  // Actions: Schedule Report
  const scheduleReport = useCallback((config) => {
    return new Promise((resolve) => {
      setLoading(true);
      setTimeout(() => {
        const newSchedule = {
          _id: `sch-${Date.now()}`,
          reportType: config.reportType,
          frequency: config.frequency,
          emailRecipients: config.emailRecipients || [],
          format: config.format || "PDF",
          nextRun: new Date(Date.now() + 24 * 60 * 60 * 1000).toISOString(),
          lastRun: "--",
          deliveryMethod: config.deliveryMethod || "Both",
          runTime: config.runTime || "08:00 AM",
          active: true
        };

        setRawSchedules(prev => [newSchedule, ...prev]);
        setLoading(false);
        toast.success("Report scheduled successfully.");
        resolve(newSchedule);
      }, 500);
    });
  }, []);

  // Actions: Update Schedule
  const updateSchedule = useCallback((id, config) => {
    return new Promise((resolve) => {
      setRawSchedules(prev =>
        prev.map(sch => (sch._id === id ? { ...sch, ...config } : sch))
      );
      toast.success("Report schedule updated successfully.");
      resolve(true);
    });
  }, []);

  // Actions: Toggle Schedule Active
  const toggleScheduleActive = useCallback((id) => {
    return new Promise((resolve) => {
      setRawSchedules(prev =>
        prev.map(sch => {
          if (sch._id === id) {
            const nextActive = !sch.active;
            toast.success(`Schedule ${sch.reportType} ${nextActive ? "enabled" : "disabled"}.`);
            return { ...sch, active: nextActive };
          }
          return sch;
        })
      );
      resolve(true);
    });
  }, []);

  // Actions: Delete Schedule
  const deleteSchedule = useCallback((id) => {
    return new Promise((resolve) => {
      setRawSchedules(prev => prev.filter(sch => sch._id !== id));
      toast.success("Report schedule deleted successfully.");
      resolve(true);
    });
  }, []);

  // Actions: Run Schedule Now
  const runScheduleNow = useCallback((id) => {
    return new Promise((resolve) => {
      const sch = rawSchedules.find(s => s._id === id);
      if (!sch) return resolve(false);

      toast.info(`Running scheduled report task for ${sch.reportType} immediately...`);
      setTimeout(() => {
        // Trigger report generation
        generateReport({
          reportType: sch.reportType,
          startDate: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString().split("T")[0],
          endDate: new Date().toISOString().split("T")[0],
          storeFilter: "All Stores",
          format: sch.format,
          includeCharts: true,
          includeSummary: true
        });

        // Update schedule last run time
        setRawSchedules(prev =>
          prev.map(s => {
            if (s._id === id) {
              return {
                ...s,
                lastRun: new Date().toISOString()
              };
            }
            return s;
          })
        );
      }, 500);

      resolve(true);
    });
  }, [rawSchedules, generateReport]);

  // Bulk Actions
  const bulkDownloadSelected = useCallback(() => {
    if (selectedRowKeys.length === 0) return;
    
    selectedRowKeys.forEach((key, idx) => {
      setTimeout(() => {
        const r = rawReports.find(item => item._id === key);
        if (r && r.status === "Completed") {
          downloadReport(r._id);
        }
      }, idx * 600); // staggering downloads
    });
    setSelectedRowKeys([]);
  }, [selectedRowKeys, rawReports, downloadReport]);

  const bulkDeleteSelected = useCallback(() => {
    if (selectedRowKeys.length === 0) return;

    setRawReports(prev => prev.filter(r => !selectedRowKeys.includes(r._id)));
    toast.success(`Deleted ${selectedRowKeys.length} reports successfully.`);
    setSelectedRowKeys([]);
  }, [selectedRowKeys]);

  const bulkExportCSV = useCallback(() => {
    const filename = `Generated_Reports_Index_${new Date().toISOString().split("T")[0]}.csv`;
    const headers = ["Report Number", "Report Type", "Date Range", "Generated By", "Created At", "Status", "Format", "Downloads"];
    const csvContent = [
      headers.join(","),
      ...filteredReports.map(r => [
        r.reportNumber,
        r.reportType,
        `"${r.startDate} to ${r.endDate}"`,
        r.generatedBy,
        r.createdAt,
        r.status,
        r.format,
        r.downloadCount
      ].join(","))
    ].join("\n");

    const blob = new Blob(["\uFEFF" + csvContent], { type: "text/csv;charset=utf-8;" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.download = filename;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    toast.success("Exported reports list as CSV!");
  }, [filteredReports]);

  return {
    loading,
    search,
    setSearch,
    reportType,
    setReportType,
    status,
    setStatus,
    generatedBy,
    setGeneratedBy,
    dateFilter,
    setDateFilter,
    customRange,
    setCustomRange,
    
    currentPage,
    setCurrentPage,
    pageSize,
    setPageSize,
    sortBy,
    setSortBy,
    sortOrder,
    setSortOrder,

    selectedRowKeys,
    setSelectedRowKeys,

    selectedReport,
    setSelectedReport,
    selectedSchedule,
    setSelectedSchedule,

    statistics,
    reportsByTypeChartData,
    reportTrendChartData,
    usersList,
    tableData: paginatedReportsTableData,
    totalRecords: filteredReports.length,

    schedulesTableData: rawSchedules,

    generateReport,
    downloadReport,
    retryReport,
    deleteReport,
    scheduleReport,
    updateSchedule,
    toggleScheduleActive,
    deleteSchedule,
    runScheduleNow,

    bulkDownloadSelected,
    bulkDeleteSelected,
    bulkExportCSV,

    refetch: () => {
      setLoading(true);
      setTimeout(() => {
        setRawReports([...mockGeneratedReports]);
        setRawSchedules([...mockScheduledReports]);
        setLoading(false);
        toast.success("Reports reloaded successfully.");
      }, 500);
    }
  };
}
